### ISSUE TITLE
/tmp/InjectionBundle14.bundle/InjectionBundle. One of the two will be used. Which one is undefined.

### ISSUE THREAD

**Issue by anyuhao** [johnno1962/injectionforxcode#102]
/tmp/InjectionBundle14.bundle/InjectionBundle. One of the two will be used. Which one is undefined.

How do you solve this Issues

**Comment by johnno1962** [comment]
It says to ignore the warning which you can. Injection will still work.

**Comment by BountyProgrammer** [comment]
@johnno1962 I have the same error.

**Comment by tianglin** [comment]
I have the same error.

**Comment by orta** [comment]
Closing as `wontfix` - this is a fundamental part of how injection works.
