### ISSUE TITLE
BundleInjection.h  Redefinition of 'file' as different kind of symbol

### ISSUE THREAD

**Issue by yilongmd** [johnno1962/injectionforxcode#104]
If it is a new project to use InjectionI is very perfect;

Unit price to join their own framework code on the problem;

Is it because my project is NoARC?

----------
In the following attached to the process, please help;

1.my project

**Comment by johnno1962** [comment]
you must have a symbol “file” in your main.m??

**Comment by yilongmd** [comment]
I am uploading the image file

**Comment by yilongmd** [comment]
![No.1](https://github.com/yilongmd/Temp/blob/master/1.jpg)
![No.1](https://github.com/yilongmd/Temp/blob/master/2.jpg)
![No.1](https://github.com/yilongmd/Temp/blob/master/3.jpg)
![No.1](https://github.com/yilongmd/Temp/blob/master/4.jpg)
![No.1](https://github.com/yilongmd/Temp/blob/master/5.jpg)
![No.1](https://github.com/yilongmd/Temp/blob/master/7.jpg)
![No.1](https://github.com/yilongmd/Temp/blob/master/8.jpg)

**Comment by johnno1962** [comment]
Find out where BundleInjection.h is included (probably your main.m) and locate where the symbol is duplicated (or are you including BundleInjection.h twice?)

**Comment by yilongmd** [comment]
https://github.com/yilongmd/Temp/
look here.

**Comment by yilongmd** [comment]
I uploaded my project.

**Comment by yilongmd** [comment]
https://github.com/yilongmd/InjectAndBeeBugTest

**Comment by johnno1962** [comment]
Look for another definition of symbol “file” in AppDelegate.h

**Comment by yilongmd** [comment]
My AppDelegate Be packaged  
Is this a problem？

**Comment by yilongmd** [comment]
#import "Bee.h"

#pragma mark -

@interface AppDelegate : BeeUIApplication
@end

**Comment by johnno1962** [comment]
Look in Bee.h

**Comment by johnno1962** [comment]
Easiest thing to do is replace #import “AppDelegate.h” in main.m with @class AppDelegate;

**Comment by yilongmd** [comment]
I try

**Comment by yilongmd** [comment]
Thank you. I'll try.

**Comment by orta** [comment]
Closing due to wrapped up :+1:
