### ISSUE TITLE
Which GIF generator app did you use in this project

### ISSUE THREAD

**Issue by aaron-elkins** [johnno1962/injectionforxcode#106]
Hi,

I wonder which GIF app did you use to make this clear GIF demo in the README on Mac?

**Comment by aaron-elkins** [comment]
The GIF looks so beautiful on Mac

**Comment by johnno1962** [comment]
It was all @orta’s doing, apparently he used GIF Brewery v3 (Mac App Store)

**Comment by aaron-elkins** [comment]
Thanks

**Comment by orta** [comment]
It's great 10/10
