### ISSUE TITLE
Need some helps

### ISSUE THREAD

**Issue by Rick630** [johnno1962/injectionforxcode#107]
Hello, I try the Plugin with my project, and press ctrl + shift + =, then the simulator performs like this capture, why that? Is there any step wrong?
<img width="487" alt="screen shot 2016-03-19 at 11 52 22 pm" src="https://cloud.githubusercontent.com/assets/11673596/13899761/cfa23fb6-ee30-11e5-980e-a5f83c5cfd53.png">

**Comment by Rick630** [comment]
Here's some logs

2016-03-20 00:17:04.835 xxx[53897:2482800] Injection attempting connection to: 127.0.0.1:31442
2016-03-20 00:17:04.877 xxx[53897:2482800] Connected to "Injection" plugin, ready to load x86_64 code.
Compiling /Users/rick/Desktop/Dev/qqsd/Code/xxx/Controller/Tips/TipsViewController.m
        1.74 real         0.26 user         1.14 sys
objc[53897]: Class TipsViewController is implemented in both /Users/rick/Library/Developer/CoreSimulator/Devices/B4A24407-7B17-43BF-B8F1-2FC11540505C/data/Containers/Bundle/Application/9B9A61BF-82A2-466D-A542-FC771878F227/xxx.app/xxx and /Users/rick/Desktop/Dev/qqsd/Code/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle2.bundle/InjectionBundle. One of the two will be used. Which one is undefined.
5 injections performed so far.
2016-03-20 00:17:07.126 xxx[53897:2482207] Ignore any warning, Swizzled TipsViewController 0x11992a388 -> 0x105f92018
2016-03-20 00:17:11.028 xxx[53897:2482207] I've been injected: <TipsViewController: 0x7fd02183f400>

**Comment by johnno1962** [comment]
You should use ctrl-=. you have unwittingly invoked the unreliable “inject and reset” which is ctrl-shift-=

**Comment by Rick630** [comment]
Awesome! It works, thanks
