### ISSUE TITLE
Can't Inject Code

### ISSUE THREAD

**Issue by scorpiozj** [johnno1962/injectionforxcode#109]
Environment: Xcode7.2.1, OS X 10.10.5, Obj-C project  
I install the plugin following the guide: build the project, and I check that the plugin exists in the directory. When I reopen the Xcode, it doesn't pop the alert which indicates Xcode is loading 3rd plugin. But at the same time, the Inject exists in `Product`.  
I create a simple view-based project, and When I try to inject the source:

1. add code to my ViewController: `- (void)injected`, and add breakpoint
2. build and run my project
3. in the injected ViewController, click: control+=

Result: 

1. After clicking, project didn't stop at the breakpoint. 
2. if I click 3 times control+=, it will pop up 3 alerts when I stop the running. The alert is attached below.

![2016-03-21 4 29 06](https://cloud.githubusercontent.com/assets/644156/13913574/20e08d12-ef83-11e5-94a6-2c9b10f12d46.png)

Please take a look!

**Comment by orta** [comment]
What does the injection console say?

**Comment by scorpiozj** [comment]
Thanks for quick response!  I check and find the console is blank.  
But I create a new project and follow the guide, the project can be injected!   
Now it seems that the existing project can't be injected.

**Comment by johnno1962** [comment]
Hi, you noramally get this message if your project doesn’t connect to injection for some reason. Wehn you run your project and try to inject, what does your Xcode debug console say? It should say something about “trying to connect to Xcode”. Is there a red “1” badge on the Xcode Icon?

**Comment by scorpiozj** [comment]
I just tested the project and found it could be rejected! 
Close this issue although didn't find why fail to connect to injection.
