### ISSUE TITLE
BundleInjection.h  Redefinition of 'file' as different kind of symbol

### ISSUE THREAD

**Issue by yilongmd** [johnno1962/injectionforxcode#111]
I replaced a brand new AppDelegate
But as long as I have the original project file will be wrong

main.m file ：
#import <UIKit/UIKit.h>
#import "AppDelegate.h"

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
    }
}

// From here to end of file added by Injection Plugin //

#ifdef DEBUG
static char _inMainFilePath[] = __FILE__;
static const char *_inIPAddresses[] = {"192.168.1.5", "127.0.0.1", 0};

#define INJECTION_ENABLED
#import "/tmp/injectionforxcode/BundleInjection.h"
#endif

**Comment by johnno1962** [comment]
try this, before #ifdef DEBUG add the following:

#define file not_file

**Comment by orta** [comment]
Closing as inactive.
