### ISSUE TITLE
identity.txt not created, removed on injection

### ISSUE THREAD

**Issue by nickkjordan** [johnno1962/injectionforxcode#115]
`identity.txt` was not created when injecting the project.  I created my own file, and console outputs a successful codesign with the identity, but after injection the file is removed.

I'm injecting onto a device if that makes a difference.  I had no issues when injecting with a Simulator on another project.

**Comment by johnno1962** [comment]
Must be related to this code in injectSource.pl:

my ($localBundle, $identity) = loadFile( $infoFile );
$localBundle =~ s@^.*/Build/@$buildRoot/@ if $buildRoot;
(my $localBinary = $localBundle) =~ s@([^./]+).app@$1.app/$1@;

unlink $infoFile if $buildRoot && !-d $localBundle;

can you try commenting out the “unlink” line?

**Comment by nickkjordan** [comment]
That works.  Is there some sort of setup that might have caused this?
