### ISSUE TITLE
App name with spaces will not build in InjectionBundle

### ISSUE THREAD

**Issue by gregpardo** [johnno1962/injectionforxcode#120]
In the example here the app name would be 'My App.app'

```
clang: error: no such file or directory: 'App.app/Frameworks'
```

What's happening is the -F linker flag is getting split some how which results in chunks of the name with spaces getting linked as flags. So you have something like this in Other Linker Flags.

```
-L'/Applications/Xcode.....
-F/Users/....My
App.app/Frameworks
-framework
Alamofire
```

So it looks to me like the -F has to do exactly what -L is doing and wrap the string in ' symbol

**Comment by johnno1962** [comment]
Hi, I’ve pushed a fix for this. Can you check it works now?

**Comment by gregpardo** [comment]
The bundle now builds so I think we can close this. I'm having some other issues though which I think are unrelated. I'll try to sort them out.
