### ISSUE TITLE
How to use  Tunable Parameters by using objective-c

### ISSUE THREAD

**Issue by csuzjq** [johnno1962/injectionforxcode#121]
using swift，I can use Tunable Parameters ，but use oc，xcode can‘t find function

**Comment by johnno1962** [comment]
you need to #import BundleInterface.h into your file or .pch file

**Comment by csuzjq** [comment]
Yes,I imported ,but it also can't find.and some people has the same question as me. 
this is my .pch ang main.m

#ifndef Prefix_pch
#define Prefix_pch
// Include any system framework and library headers here that should be included in all compilation units.
// You will also need to set the Prefix Header build setting of one or more of your targets to reference this file.

#endif /* Prefix_pch */

// From here to end of file added by Injection Plugin //

#ifdef DEBUG
#define INJECTION_ENABLED

#import "/tmp/injectionforxcode/BundleInterface.h"
#endif


int main(int argc, char * argv[]) {
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
    }
}

// From here to end of file added by Injection Plugin //

#ifdef DEBUG
static char _inMainFilePath[] = __FILE__;
static const char *_inIPAddresses[] = {"10.0.0.23", "192.168.0.235", "127.0.0.1", 0};

#define INJECTION_ENABLED
#import "/tmp/injectionforxcode/BundleInjection.h"
#endif

i use two ways.
1. 
- (void)changeColor
{
    self.view.backgroundColor = INColors[0];
}
but it can't find INColors

the second ways,i use delegate  and orrvride the two functions.
 [NSObject inSetDelegate:self forParameter:0];

- (void)inParameter:(int)tag hasChanged:(float)value{
//    _label.text = [NSString stringWithFormat:@"%f",value];
    NSLog(@"------%f",value);
}
- (void)inColor:(int)tag hasChanged:(id)value
    
but  xcode can't find  [NSObject inSetDelegate:self forParameter:0];

something wrong with installing?

**Comment by johnno1962** [comment]
Is DEBUG defined? Is your pch being compiled? Include BundleInterface.h in the source you are injecting from if there is any doubt.

**Comment by csuzjq** [comment]
I try to Include BundleInterface.h in the source I  injected from,but it does't work. so amazing !

**Comment by johnno1962** [comment]
Are thhings not compiling or not the parameters not working. Is the project “patched"

**Comment by csuzjq** [comment]
wonderful ,I install it again.and it work !but the color can't be changed. here are my code
`#import "ViewController.h"
#ifdef DEBUG
#define INJECTION_ENABLED
#import "/tmp/injectionforxcode/BundleInterface.h"
#endif
@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    [NSObject inSetDelegate:self forParameter:0];
}

- (void)injected
{
    NSLog(@"I've been injected: %@", self);
}

- (void)changeColor
{
    self.view.backgroundColor = INColors[0];
}

- (void)inParameter:(int)tag hasChanged:(float)value{
    NSLog(@"---------%f",value);
}
- (void)inColor:(int)tag hasChanged:(id)value{
    UIColor *color = (UIColor *)value;
    self.view.backgroundColor = color;
    [self viewDidLoad];
}
    // Do any additional setup after loading the view, typically from a nib.
- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}
`

**Comment by johnno1962** [comment]
Colors are different, you need to add to viewDidLoad:
+ (void)inSetTarget:(id)target action:(SEL)action forColor:(int)tag;

**Comment by csuzjq** [comment]
cool! perfect! thank you johnno! here are my code. 
```objective-c
- (void)viewDidLoad {
    [super viewDidLoad];
     UIButton *button = [[UIButton alloc] initWithFrame:CGRectMake(100, 100, 100, 100)];
    [button setTitle:@"TestButton" forState:UIControlStateNormal];
    [button setTitleColor:[UIColor blueColor] forState:UIControlStateNormal];
    [button addTarget:self action:@selector(test) forControlEvents:UIControlEventTouchUpInside];
    [self.view addSubview:button];
    
    _label = [[UILabel alloc] initWithFrame:CGRectMake(100, 300, 100, 100)];
    _label.textColor = [UIColor redColor];
    [self.view addSubview:_label];
    
    [NSObject inSetDelegate:self forParameter:0];
    [NSObject inSetTarget:self action:@selector(inColor:hasChanged:) forColor:0];
    
}
- (void) test{
      _label.text = @"hello!";
}

- (void)inParameter:(int)tag hasChanged:(float)value{
    NSLog(@"------%f",value);
}
- (void)inColor:(int)tag hasChanged:(id)value{
    self.view.backgroundColor = (UIColor *)value;
}
```

**Comment by johnno1962** [comment]
Does that work?? It should really be:
```
    [NSObject inSetTarget:self.view action:@selector(setBackgroundColor) forColor:0];
```

**Comment by csuzjq** [comment]
yes ,it work.you can try by yourself

**Comment by johnno1962** [comment]
opps setBackgroundColor:

**Comment by csuzjq** [comment]
It works! so there are two ways!
