### ISSUE TITLE
Injection fails if a directory name contains the "&".

### ISSUE THREAD

**Issue by VincentSit** [johnno1962/injectionforxcode#128]
Hi, I just found this issue. Other cases using is working properly. Is this a bug or if I should rename the directory?

![1 pic_hd](https://cloud.githubusercontent.com/assets/4084679/14891995/8b95fb52-0d9b-11e6-9de2-454e325f4bf7.jpg)
![qq20160428-0](https://cloud.githubusercontent.com/assets/4084679/14891998/8e62183e-0d9b-11e6-91d0-d902004647c4.png)
![qq20160428-1](https://cloud.githubusercontent.com/assets/4084679/14891999/8e939d82-0d9b-11e6-97e6-09b372dd7bbb.png)

**Comment by johnno1962** [comment]
Thanks for the report. You’ll have to rename the dir I’m afraid.

**Comment by VincentSit** [comment]
@johnno1962 Ok, thank you.

**Comment by orta** [comment]
Closing as `wontfix`
