### ISSUE TITLE
Injection doesn't work using autolayout with masonry and non-ascii project path.

### ISSUE THREAD

**Issue by BiggerGao** [johnno1962/injectionforxcode#129]
1.When I press control + '=' to build my project it'll fall if my project path like this /Users/Echo/计算机设计大赛/ElderlyCare/ElderlyCare.xcworkspace.

The primary problem 2.
I use autolayout with masonry.When I press control + '=' it could build successfully but without any changed in simulator.

**Comment by BiggerGao** [comment]
It seem like it can't use under non-ascii path.
#105 

But is there a way to fix my second problem?

**Comment by johnno1962** [comment]
I’m not sure what your second problme is. Do you need to call viewDidLoad: on injection?

**Comment by BiggerGao** [comment]
Tks. I have solved my problem rewriting the injection: method and put my ui code segment with masonry in it.I previously found the ui codes in viewDidLoad: could also be refreshed when I injected project again,but this time it plays up.
