### ISSUE TITLE
xcode 7.3 怎么用不了啊,

### ISSUE THREAD

**Issue by thomas0326** [johnno1962/injectionforxcode#132]
** Could not codesign as 'iPhone Developer': /Users/Jeffery/Desktop/twotiger/twotiger_ios/iOSInjectionProject/build/Debug-iphoneos/InjectionBundle4.bundle ***   at /Users/Jeffery/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 57. 	main::error('Could not codesign as 9hone Developerø/Users/Jeffery/De...') called at /Users/Jeffery/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 509 *** Bundle build failed ***

**Comment by johnno1962** [comment]
This is normally https://github.com/johnno1962/injectionforxcode/issues/41

**Comment by luoerming** [comment]
兄弟这里是美国，不能用中文

**Comment by johnno1962** [comment]
This is due to Xcode 8 support. Please use Project/Injection Plugin/Open Bundle Project to edit the bundle project to set a valid codesigning identity.

**Comment by luoerming** [comment]
Error loading /Users/carroll/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/InjectionLoader.bundle/InjectionLoader:  dlopen(/Users/carroll/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/InjectionLoader.bundle/InjectionLoader, 265): no suitable image found.  Did find:
	/Users/carroll/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/InjectionLoader.bundle/InjectionLoader: required code signature missing for '/Users/carroll/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/InjectionLoader.bundle/InjectionLoader'

Hey, @johnno1962 I don't know what I did wrong.

**Comment by johnno1962** [comment]
Is tis Xcode 8? It requires that This bundle be code signed. The new plugin shold do this in one of it’s run script build phases.

**Comment by luoerming** [comment]
Yes, its run in Xcode 8, I am already signed. And I can load Alcatraz but I can't run injection Plug-in.

This is the step i signed.

`sudo ./unsign /Applications/Xcode.app/Contents/MacOS/Xcode`

And rename 'Xcode.unsigned ' to Xcode. and then restart Xcode load Alcatraz Bundle.

`find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`

Finally signed Xcode Plug-ins

Which step I did wrong? Please help me thank you. @johnno1962

**Comment by johnno1962** [comment]
Problem for the error you list above is InjectionLoader.bundle not being code signed. Do you have the most recent version of Injection plugin compiled from source? It has a run script build phase which does this.

**Comment by luoerming** [comment]
<img width="979" alt="qq20160923-0 2x" src="https://cloud.githubusercontent.com/assets/1733426/18780299/650a76f6-81af-11e6-8743-a30e940efe9c.png">

<img width="831" alt="qq20160923-1 2x" src="https://cloud.githubusercontent.com/assets/1733426/18780356/bd9fcd16-81af-11e6-8968-095d4eb9fc06.png">

Sorry, I do not understand what you mean. I try to install again , But still wrong ...

**Comment by johnno1962** [comment]
You have a duplicte of key “iPhone developer erming loo XXXXX" in your keychain. Check for this in the /Application/Utilities/Keychain Access app and delete the older one. The other error, I don’t know the cause.

**Comment by luoerming** [comment]
I'm sorry, I renounce the use of this plug-in,  I really can not solve, if you can document details installation instructions Xcode 8 tutorial, I will be grateful to you.

Now you can turn off this issues, Thank you.

**Comment by thomas0326** [comment]
@luoerming   I'm sorry, I'm newer, Thank you!
