### ISSUE TITLE
xcode7.3  build error  , the class which is  a subclass of cocoapod

### ISSUE THREAD

**Issue by Susong** [johnno1962/injectionforxcode#134]
here is the error msg :

The following build commands failed:  CompileC build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/Objects-normal/x86_64/BundleContents.o BundleContents.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (1 failure)  *** Build Failed with status: 65. You may need to open and edit the bundle project to resolve issues with either header include paths or Frameworks the bundle links against.    at /Users/benssng/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 57.  main::error('Build Failed with status: 65. You may need to open and edit t...') called at /Users/benssng/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 461  Bundle build failed ***

thank you

**Comment by johnno1962** [comment]
The actual error is a little further up the log. Can youi paste it in?

**Comment by orta** [comment]
Closing as inactive.
