### ISSUE TITLE
AppCode installation issues

### ISSUE THREAD

**Issue by lyahdav** [johnno1962/injectionforxcode#135]
This is an awesome plugin! I got it working very easily in Xcode, but I primarily use AppCode. I followed the instructions [here](https://github.com/johnno1962/injectionforxcode#user-content-use-with-appcode), but I had a few issues (AppCode version 2016.1):

1. I wasn't able to install the plugin by copying it to the directory specified. Instead I had to download the .jar to my Downloads folder, go into AppCode preferences, choose "Install plugin from disk", and restart the IDE.
2. After the plugin was installed, it wasn't clear how to inject source. I assumed the same keyboard shortcut as the Xcode plugin, and that worked, but it would be nice to explain that in the instructions (and that it adds other menu items to the Run menu).
3. The "Patch project for Injection" menu item changed a pbxproj file that was for our linter, completely not needed to get this to work. The linter project happens to be version controlled as a subfolder within the main project folder, which is how I guess it found this other project.
4. It's nice that the Xcode version doesn't require any modifications to the project. Is this not possible with AppCode? As a workaround I added main.m to my `.git/info/exclude` file, but this very much seems like a hack.

**Comment by johnno1962** [comment]
Hi, do you want to open a PR on the README? That would be a big help.

**Comment by lyahdav** [comment]
I created PR https://github.com/lyahdav/injectionforxcode/pull/1 for this.
Any thoughts on items 3 or 4 from my list above?

**Comment by johnno1962** [comment]
Can you open a pull request on your change against this repo please then I can merge it? Can’t fix 3 or 4 I’m afraid as the patch to the project is required for injection to work and AppCode only works with “patched” injection.

**Comment by lyahdav** [comment]
Done in https://github.com/johnno1962/injectionforxcode/pull/144.

**Comment by johnno1962** [comment]
Cheers
