### ISSUE TITLE
Can't Working On a Device

### ISSUE THREAD

**Issue by AmySong** [johnno1962/injectionforxcode#137]
My Objective - c project
1:
main.m file:
***********************************
#import <UIKit/UIKit.h>
#import "AppDelegate.h"

int main(int argc, char * argv[]) {
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
    }
}

// From here to end of file added by Injection Plugin //

#ifdef DEBUG
static char _inMainFilePath[] = __FILE__;
static const char *_inIPAddresses[] = {"192.168.5.58", "192.168.2.1", "169.254.206.76", "127.0.0.1", 0};

#define INJECTION_ENABLED
#import "/tmp/injectionforxcode/BundleInjection.h"
#endif
***********************************************
2:
after  control+=   , there is bad ,

********************
*** Could not codesign as '': /Users/songdan/Desktop/luxclub_ios/iOSInjectionProject/build/Debug-iphoneos/InjectionBundle2.bundle ***   at /Users/songdan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 57. 	main::error('Could not codesign as  : /Users/songdan/Desktop/luxclub_io...') called at /Users/songdan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 513 *** Bundle build failed *** 
********************
3:I find two ways from internet,
one way:  i remove iOSInjectionProject from project,  'Build Phases' add 'Run Script',  the last build ,but invalid.

**Comment by AmySong** [comment]
![2016-05-19 10 52 31](https://cloud.githubusercontent.com/assets/18390306/15384625/913e0dae-1dce-11e6-9e58-0c0f59477b93.png)

**Comment by johnno1962** [comment]
It’s not picking up a codesigning identity for your project:

```
my $infoFile = "$archDir/identity.txt";

if ( !-f $infoFile ) {
    my %VARS = `$xcodebuild -showBuildSettings $config` =~ /    (\w+) = (.*)\n/g;
    IO::File->new( "> $infoFile" )->print( "$VARS{CODESIGNING_FOLDER_PATH}\n$VARS{CODE_SIGN_IDENTITY}\n");
}
```

**Comment by AmySong** [comment]
![2016-05-20 10 45 06](https://cloud.githubusercontent.com/assets/18390306/15415822/0e60f36a-1e78-11e6-8440-1c5c2b4b8636.png)
identity.txt   does't exist.

**Comment by johnno1962** [comment]
Do you have your build locations preference set to the non-default? Try commenting out this line in injectSource.pl (Menu: Product/Injection  Plugin/Open Resource/Code Injection Script)

138: unlink $infoFile if $buildRoot && !-d $localBundle;

**Comment by AmySong** [comment]
That problem has been solved.but, there has a new problem.

Here are the tips

![Uploading 屏幕快照 2016-05-20 下午3.55.11.png…]()
![Uploading 屏幕快照 2016-05-20 下午3.54.49.png…]()
