### ISSUE TITLE
Injection seems to fail almost silently 

### ISSUE THREAD

**Issue by joedaniels29** [johnno1962/injectionforxcode#142]
When I inject, heres what I do get
```
objc[18574]: Class BundleInjection is implemented in both /Users/Joe/Library/Developer/CoreSimulator/Devices/BADC197C-6E2E-4BDA-92ED-4CEBFE4325DC/data/Containers/Bundle/Application/90EBBC5C-9909-46D7-A0D7-6FB3C91A8A73/EpiWatch.app/EpiWatch and /Users/Joe/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/InjectionLoader.bundle/InjectionLoader. One of the two will be used. Which one is undefined.
``` 
None of the classes seem to reload, and the injected method isn't getting called. How can I go about debugging this? Idk where injectionforxcode logs if anywhere.

**Comment by joedaniels29** [comment]
As soon as I post I solved it. its the Appcode injection patch in main.m that seems to be prohibiting the reload from functioning properly in Xcode.

**Comment by joedaniels29** [comment]
Both xc and app code injection are failing because of this issue though, which I don't understand. Any idea how I can debug this one?

```
2016-06-09 14:30:23.264 EpiWatch[23121:1097572] Error loading /Users/Joe/Projects/Mine/epiwatch/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle2.bundle/InjectionBundle:  dlopen(/Users/Joe/Projects/Mine/epiwatch/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle2.bundle/InjectionBundle, 265): Symbol not found: _OBJC_CLASS_$_GAI
  Referenced from: /Users/Joe/Projects/Mine/epiwatch/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle2.bundle/InjectionBundle
  Expected in: flat namespace
 in /Users/Joe/Projects/Mine/epiwatch/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle2.bundle/InjectionBundle
2016-06-09 14:30:23.264 EpiWatch[23121:1097572] Bundle Load Error
2016-06-09 14:30:23.264 EpiWatch[23121:1098241] *** Bundle has failed to load. If this is due to symbols not found, this may be due to symbols being hidden from dynamic libraries. ***
2 injections performed so far.
```

**Comment by johnno1962** [comment]
Hi, this is gnerally to do with Google analytics if you are using it in the class being injected as they make their symbols non-public visibiliyt so they can not be linked against. I’m afraid there is no solution to this. Other classes that do not refer to the GAI class should inject ok.

**Comment by joedaniels29** [comment]
Thank you so much for the feedback! 

 —Looks like you're right. This project has GA all throughout it, but only sparsely in this file. By commenting out the references (who cares about analytics anyways?) and setting the VC class to UIViewCOntroller, it all worked. Thanks again!
