### ISSUE TITLE
... First time learning of project, one second ...

### ISSUE THREAD

**Issue by xiaolong11** [johnno1962/injectionforxcode#146]
*** Build Failed with status: 65. You may need to open and edit the bundle project to resolve issues with either header include paths or Frameworks the bundle links against. ***   at /Users/yangyang/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 57. 	main::error('Build Failed with status: 65. You may need to open and edit t...') called at /Users/yangyang/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 465 *** Bundle build failed ***

**Comment by johnno1962** [comment]
The real error is just before this in the logs.

**Comment by xiaolong11** [comment]
Can you understand Chinese?Let's communicate in Chinese?
