### ISSUE TITLE
hello,The get method is invalid

### ISSUE THREAD

**Issue by biggercoffee** [johnno1962/injectionforxcode#150]
getter method is invalid.

before
![9b8674c9-6627-437e-8fc3-001bafa938b5](https://cloud.githubusercontent.com/assets/12556487/16680820/f80089e6-4523-11e6-97e9-f30864ebd277.png)

after
![ba89191f-6e55-4bd2-b938-917b8835690d](https://cloud.githubusercontent.com/assets/12556487/16680814/e9aa4c10-4523-11e6-94c1-de3e71ac733c.png)

**Comment by johnno1962** [comment]
HI, This sounds like it might be a problem. Can you explain more please.

**Comment by biggercoffee** [comment]
I have a detail viewcontroller from rootviewcontroller push in, Call Model to display the viewcontroller.
Input a NSLog in the get method of the model, and then type the control + '=', prompt success, but the actual failure.

**Comment by johnno1962** [comment]
Ah, I see now. Injection does not inject getters or setters on properties.

**Comment by biggercoffee** [comment]
oh,Is this a bug???
Is there a way to solve???

**Comment by johnno1962** [comment]
This is done on purpose as it seemed unnecessary

**Comment by biggercoffee** [comment]
ok, thanks
