### ISSUE TITLE
Bundle Load Error

### ISSUE THREAD

**Issue by mstail** [johnno1962/injectionforxcode#156]
Bundle has failed to load. If this is due to symbols not found, this may be due to symbols being hidden from dynamic libraries.

Expected in: flat namespace
 in /Users/mstail/Desktop/fanwei/hospital/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle2.bundle/InjectionBundle

Please help to solve the above problems. Thanks~

**Comment by johnno1962** [comment]
The must be some undefined symbols loading. Check your Xcode console for details.
