### ISSUE TITLE
When multiple targets exist in project, bundle compilation fails

### ISSUE THREAD

**Issue by zintus** [johnno1962/injectionforxcode#158]
Hello and thanks for awesome project!

Bundle compilation fails for me being unable to find frameworks to link with. After some research i've found, that in `injectionSource.pl:130` it's undefined for which target build settings should be shown. In my case xcodebuild selects wrong target, therefore rendering derived inlcude paths wrong.

Maybe it's related to target selection, but generated framework search path contains comma in the middle of path.  `-F'/Users/zintus/Library/Developer/Xcode/DerivedData/IO-effdteicbasathfqikibhumkmzvc/Build'/Products/Debug-iphonesimulator`

Thanks.

**Comment by johnno1962** [comment]
Hi, from memory, the extra quote is intentional.

**Comment by zintus** [comment]
What about target selection?

**Comment by johnno1962** [comment]
Unfortunately injection doesn’t know about targets. Can you move the correct target in your project to make it the default?

**Comment by zintus** [comment]
Reordering scheme in Xcode doesn't help, but editing scheme container directly helps. 

Thank you :)
