### ISSUE TITLE
ld: framework not found GoogleMapsBase for architecture x86_64

### ISSUE THREAD

**Issue by jyliang** [johnno1962/injectionforxcode#162]
[injection.zip](https://github.com/johnno1962/injectionforxcode/files/437861/injection.zip)

Please see attached project for demonstration of the problem.
Injection on FirstViewController will result in error.

Env:
XCode 7.3

To Repo:
1. pod install
2. inject on FirstViewController and notice the error
3. comment out: import GoogleMaps
4. inject again and notice the injection is successful

what seems to be the problem here?

**Comment by johnno1962** [comment]
Most likely this is because it is not finding the framework. You may need to adjust your Framework search path in injection’s “bundle project”.

**Comment by jyliang** [comment]
Thanks the for the fast response!
Solved!
Solution:
Add this to the Framework Search Paths in the InjectionBundle project:
$(PROJECT_DIR)/.. (this goes back up to the original project folder)
and marked it recursive
