### ISSUE TITLE
EXC_BAD_ACCESS when injecting

### ISSUE THREAD

**Issue by timothycosta** [johnno1962/injectionforxcode#164]
I'm having trouble with crashing during injection *sometimes*.  I haven't been able to figure out what is triggering this.  Sometimes quitting and restarting Xcode fixes the issue, sometimes not.  This is in Xcode 8, so I don't know if it's worth looking at yet or not.

`BundleInjection.h line 650 - EXC_BAD_ACCESS`
`if ( ![bundle load] )`

There are no errors in the console:
```
Compiling /Users/timothycosta/Desktop/lingq4.0/iLingQ/iLingQ/Views/LessonView/Popups/BluePopup.m
        0.22 real         0.16 user         0.04 sys
... First time learning of project, one second ...
```

However, "first time learning of project" is not correct.

**Comment by johnno1962** [comment]
Wait until Xcode 8 comes out (next week?) and I’ll release new code supporting Swift3. There can be problems if you are using -injected methods.

**Comment by timothycosta** [comment]
I don't think this is related to swift 3 or injected methods.  I'm not using either.  I only upgraded my project to use 2.3 and I'm not working in swift.  I just have some libraries that use it.  

If you have something ready now, would you mind sending it to my user name at gmail.com?  And if you think this might be fixed by whatever you've got coming up, feel free to close this.

**Comment by johnno1962** [comment]
OK, I’ve sent it through. let me know if you have any problems.
