### ISSUE TITLE
Shell Script Invocation Error

### ISSUE THREAD

**Issue by andrewwormald** [johnno1962/injectionforxcode#173]
So I keep getting the following error with Xcode 8.0 ~> `Command /bin/sh failed with exit code 1`

I have deleted derived data, cleaned the project, gone to run script and unselected options and tried, and tried with them selected also but nothing works

Any solution or anyone actually getting the same error?

running on macOS v 10.12

**Comment by johnno1962** [comment]
Is this building the plugin or when you inject?

**Comment by aaasun** [comment]
@johnno1962 
same error when building the InjectionPluging.xcodeproj
xcode version:xcode 8.0 (8A218a)

**Comment by johnno1962** [comment]
You’ll have to provide more of the logs from the injection console before I can know what your problem is.
