### ISSUE TITLE
Ambiguous developer

### ISSUE THREAD

**Issue by zoli-halcyon** [johnno1962/injectionforxcode#174]
Hi,

in my keychain I have two iPhone developer certificates. Even if I set the code signing identity in the project's settings (both project and target), the plugin can't determine which identity to use from the keychain. ("[...] Codesigning with identity 'iPhone Developer' for iOS device  iPhone Developer: ambiguous [...]")
Is there a way to set one?
Thanks,
Zoli.

**Comment by johnno1962** [comment]
Have a look here: https://johntmcintosh.com/blog/2016/10/03/code-injection-ios

**Comment by zoli-halcyon** [comment]
Thanks!
