### ISSUE TITLE
Crash related to non-NSObject class

### ISSUE THREAD

**Issue by krzat** [johnno1962/injectionforxcode#178]
App crashes if my view controller has a property that isn't NSObject.
The crash happens in `ivar_getTypeEncodingSwift3` method.

Minimal code:

```
import UIKit

class Foo {
}

class ViewController: UIViewController {
    let foo = Foo()
    
    func injected() {
    }
}
```

**Comment by johnno1962** [comment]
Thanks for the report. I’m afraid this seems to be the case if members do not inherit from NSObject and I’m not in a position to fix this at the moment. Please see https://github.com/johnno1962/injectionforxcode/issues/177

**Comment by krzat** [comment]
Wait, so `injected` method is the problem? If that's the case, then maybe it's support should be removed? It's easy enough to register for notification.

**Comment by johnno1962** [comment]
Objective-C users find it useful so I’ll leave it in for now. I’ll try to work out what the problem is with Pure Swift instances if I get the time.
