### ISSUE TITLE
Xcode 8.1 

### ISSUE THREAD

**Issue by prefect42** [johnno1962/injectionforxcode#181]
When compiling Injection on unsigned Xcode 8.1 (8B62) no menu items are added.
There was no New Plugins Alert on restart.
The plugin is in the Plugins Folder in Application Support though.

Did Apple remove Plugins support completely in 8.1?

**Comment by prefect42** [comment]
Ok it seems the new UUID was missing in the plist: 
DA4FDFD8-C509-4D8B-8B55-84A7B66AE701 should be added

**Comment by eilianlove** [comment]
I'm also using Xcode8, but the injection doesn't work, although `"I've been injected: (self)"` had shown in the console. @prefect42

**Comment by johnno1962** [comment]
UUID for Xcode 8.1 and Xcode 8.2 beta added
