### ISSUE TITLE
Bundle build failed 

### ISSUE THREAD

**Issue by ober01** [johnno1962/injectionforxcode#184]
log : 
* Learnt compile failed ***   at /Users/admin/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 57. 	main::error('Learnt compile failed') called at /Users/admin/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 350

**Comment by ober01** [comment]
and xcode logs:
<unknown>:0: error: cannot open file '/var/folders/gy/dms6sh0x52721rsvwn4g44qm0000gn/T/sources-e0f20c' (No such file or directory)
<unknown>:0: error: this mode requires at least one input file

**Comment by johnno1962** [comment]
Could be because your project has > 128 swift source files?
