### ISSUE TITLE
error: this mode requires at least one input file

### ISSUE THREAD

**Issue by hashemp206** [johnno1962/injectionforxcode#187]
when I inject source, I see this error and injection fails:

`Connected to "Injection" plugin, ready to load x86_64 code.
Compiling /Users/hashem/Desktop/MyApp 2/MyApp/Tabs/Menu/View/Cell/MenuItemCell.swift
<unknown>:0: error: cannot open file '/Users/hashem/Desktop/MyApp' (Is a directory)
<unknown>:0: error: this mode requires at least one input file`

it seems injection plugin has some problem with spacing in folder name.

do  you have any idea to solve this?

**Comment by johnno1962** [comment]
I’m afraid injection does not support spaces in the path to the project.

**Comment by hashemp206** [comment]
if possible add a hint in error message to clearly specify error origin.

thanks
