### ISSUE TITLE
Launch "Inject source" form the command line

### ISSUE THREAD

**Issue by s4cha** [johnno1962/injectionforxcode#189]
Hi there,

Love the library, heavy setup but worth the effort ! 

To go a step further, I would like to have kicker watch the files that changed and automatically launch `"Inject Source"` for us. (yeah I'm lazy). In essence, is there a way to trigger `Inject Source` from the command line?

Thanks so much :)

**Comment by johnno1962** [comment]
Hi, there isn’t as way to launch from the command line as it needs information from Xcode but injection has it’s own file watcher which may do what you’re after. Open "File/Injection Plugin/Tunable App Parameters”. The preference is “File Watcher”. Not sure how much it gets used so let me know if there are any problems.

**Comment by s4cha** [comment]
Thanks a ton for your fast answer, I'll try it and report back :)

**Comment by s4cha** [comment]
Wow, This is exactly what I was looking for! Somehow I missed it.
Maybe mentioning the watcher in the readme? This is a killer feature :)
Have an awesome day !

**Comment by johnno1962** [comment]
I’ve added a note to the README. Thanks for pointing this out.
