### ISSUE TITLE
Keyboard shortcut not working

### ISSUE THREAD

**Issue by vbklv** [johnno1962/injectionforxcode#195]
The keyboard shortcut to Inject Code is not working within Xcode 8.2.1.

I have set it to `Cmd+Shift+\` in `System Preferences -> Keyboard -> Shortcuts -> Services` against Inject Code but Xcode doesn't react when I am using the shortcut.

I tried restarting Xcode to no avail.
In `Xcode -> Services` menu it says `No Services Apply`.

I am using the standalone Injection app on MacOS 10.12.2

What is the magic to make it work?

**Comment by zenangst** [comment]
@vbklv services is a bit weird, if you select some text in Xcode before going into Services, then it should show up.

**Comment by vbklv** [comment]
@zenangst Thanks, it worked and showed the services. But still, the shortcut that I've set to Inject Code is not working within Xcode.

**Comment by johnno1962** [comment]
I’ve seen work inside Xcode but it has so many shortcuts itself you have to be careful not to have a clash.

**Comment by vbklv** [comment]
@johnno1962 @zenangst actually Inject Source worked when some text was first selected. Now the problem is that it leaks and takes up all the memory. See screenshots:

![screen shot 2017-01-17 at 10 35 42](https://cloud.githubusercontent.com/assets/8736853/22015183/4aa9916e-dca1-11e6-8366-28adf8c8eebc.png)

![screen shot 2017-01-17 at 10 35 33](https://cloud.githubusercontent.com/assets/8736853/22015182/4a95b9aa-dca1-11e6-83ff-2f0edb92133d.png)

If Inject Source is called within the Injection app, it works fine.

**Comment by johnno1962** [comment]
I’ve not seen that!

**Comment by vbklv** [comment]
I tried restarting XCode and all, but to no avail. It still leaks.

**Comment by johnno1962** [comment]
Seems to be in an infinte loop/recursion. Can you try running the app from the command line and see if it prints anything useful:

$ /Applications/Injection.app/Contents/MacOS/Injection

**Comment by lifubo** [comment]
I have same problem about memoy leak! The problem is that the more the times of injection , the bigger the size of memory!

**Comment by lifubo** [comment]
and the more the times of injection , the longer the time of injection!
![76d28d49-9a3e-4807-b456-d26ce997b982](https://cloud.githubusercontent.com/assets/12093368/22049150/8e410a80-dd6c-11e6-8924-e2352ec60833.png)

**Comment by vbklv** [comment]
`<div class=error>Could not list directory file:///../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../</div>
<div class=error>Could not list directory file:///../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../</div>
<div class=error>Could not list directory file:///../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../</div>
<div class=error>Could not list directory file:///../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../</div>
<div class=error>Could not list directory file:///../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../</div>
`

**Comment by johnno1962** [comment]
Thanks very helpful thanks. Not sure what the problem is but I know where it is now.

**Comment by johnno1962** [comment]
I’ve uploaded a new version which while it may not solve your problem will at least not loop like this. Can you give it a try?

**Comment by vbklv** [comment]
Confirmed, it doesn't solve the problem but at least it doesn't loop :)

![screen shot 2017-01-18 at 11 37 02](https://cloud.githubusercontent.com/assets/8736853/22060785/8ca117e6-dd72-11e6-8bcc-5b0592665df1.png)

**Comment by johnno1962** [comment]
Would you like to TeamView so I can see whats going on? If so send details to injectionapp at johnholdsworth.com

**Comment by johnno1962** [comment]
I’ve uploaded a version which logs the file it is trying to find the project for if you want to let me know the output.

**Comment by dimohamdy** [comment]
I face this problem but when you select code and press your shortcut that's work

**Comment by ybeapps** [comment]
I think I have the same problem.. Injection not working when executed with shortcut (first time try..)

It's also annoying to select text for the shortcut to do something...
It took me a whole hour to find out by myself the text selection trick :(

It's hard to be new in something.... ;-)

**Comment by ybeapps** [comment]
Hi again... I don't understand about OS X services nothing, but:

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/SysServices/Articles/properties.html

In the docs (about the plist file) there is the next statement:
**NSRequiredContext** is a dictionary that can be used to limit when the service appears. Through judicious use of NSRequiredContext, you can ensure that your service appears only when it applies and does not clutter the Services menu when it is not applicable.
**Note: Always include this property, even when you do not require any filtering (in which case you specify an empty dictionary as the value). Otherwise the system registers your service, but does not automatically present it in the Services menu.**

I don't see it in the injector app... (I couldn't add it too, maybe it's deprecated or something? I know nothing about all that stuff)

I hope it helps =]

**Comment by johnno1962** [comment]
Thanks very much for this info. I missed this page. I can’t see a way the requirement that users select some text can be avoided though.

**Comment by ybeapps** [comment]
Just add empty array, it works!!
And it's in the docs: 
Note: Always include this property, even when you do not require any filtering (in which case you specify an empty dictionary as the value). 
Otherwise the system registers your service, but does not automatically present it in the Services menu.

That's exactly what's happening now :)



‫ב-19 בינו׳ 2017, בשעה 11:13, ‏‏John Holdsworth ‏<notifications@github.com> כתב/ה:‬

**Comment by johnno1962** [comment]
Thanks, I’ve added this value to an updated app version. I think you still need to do two things to have the services menu entry com up: Enabled it in Sytem Preferences/Keyboard/Shotcuts and have some text selected.

**Comment by ybeapps** [comment]
ur right... Is there a way I can try to fix it myself instead of commenting annoying nonsense?

**Comment by johnno1962** [comment]
how do you mean?

**Comment by ybeapps** [comment]
what should I clone to be able to build by myself?
I can't find in the repository the plist file that defines the service so I can play with it and build it for testing...

**Comment by johnno1962** [comment]
The source is not avilable at the moment though you should be able to edit the Info.plist in the distributed app if you want to try a few things. Services are a pretty arcane legacy feature of OSX though and I’m not sure you’ll be able to use a service that expects a string without a selection :(

**Comment by zenangst** [comment]
@johnno1962 maybe you could implement a global shortcut for injection that is configurable in a preference pane? It could also be scoped to when `Xcode` is the active application.

**Comment by johnno1962** [comment]
Isn’t what a service is? Is there something else I’m not aware of.. tell me more.

**Comment by zenangst** [comment]
I was thinking of something like this -> https://github.com/davedelong/DDHotKey

**Comment by ybeapps** [comment]
I tried before to change the plist in your app and reinstall... I got crash for checksum failed ;) your app is surely protected by Apple...

I think that service can be available anytime... but that's just what I think... I have a Mac for only one year... I'm not so familiar with all it has.. Services in OS X are new to me


‫ב-24 בינו׳ 2017, בשעה 23:17, ‏‏John Holdsworth ‏<notifications@github.com> כתב/ה:‬

**Comment by johnno1962** [comment]
looks very intersting. In truth, the “must select text” thing is sucking. I’ll take a look at DDHotKey thanks!

**Comment by johnno1962** [comment]
I’ve uploaded a new version that defines a HotKey of control-= for injection which is indeed much better though you still need to remember to save the file. Not sure how to scope it to Xcode being active or even if that would be a good idea. Feedback welcome!

**Comment by ybeapps** [comment]
Thanks!
I'll check this out

If you want to limit your service to Xcode only you can use (again) NSRequiredContext

Add a value in there as in the docs:

NSApplicationIdentifier is a bundle ID as a string or an array of such IDs. Your service will appear only if the bundle ID of the current application matches one of the given bundle IDs. For example, you could use this to limit a service to appear only in Xcode or in the Finder.

‫ב-25 בינו׳ 2017, בשעה 1:12, ‏‏John Holdsworth ‏<notifications@github.com> כתב/ה:‬

**Comment by johnno1962** [comment]
Doesn’t that only work for services? The new code is using a Carbin HotKey (an even older API)

**Comment by ybeapps** [comment]
You're right, I thought you asked about services...


‫ב-25 בינו׳ 2017, בשעה 9:49, ‏‏John Holdsworth ‏<notifications@github.com> כתב/ה:‬

**Comment by ybeapps** [comment]
Works great Thanks!! You can mark the issue as resolved =]

**Comment by ybeapps** [comment]
I must add.. your plugin makes Stevia great!! =]
now it's starting to be fun!!

**Comment by johnno1962** [comment]
Happy to hear it.
