### ISSUE TITLE
Error with iOS 8.4 and iPhone 4S simulator

### ISSUE THREAD

**Issue by vbklv** [johnno1962/injectionforxcode#196]
When I try to Inject Source from the Injection app menu on iOS 8.4 running on iPhone 4S simulator, I get this error and injection is not possible:

```
Injection Error:
(os/kern) invalid argument
```

![screen shot 2017-01-18 at 10 27 49](https://cloud.githubusercontent.com/assets/8736853/22058337/d7500cb6-dd68-11e6-9498-8e519425093a.png)

**Comment by johnno1962** [comment]
Sorry, you need to patch the project for 32 bits.

**Comment by bonyadmitr** [comment]
@johnno1962 
Hi! How can I "patch the project for 32 bits"?

> Injection Error:
> Injection only possible for 64 bit targets

I have this error for iPhone 4s and 5.
I use latest standalone Injection app, Swift 3, Xcode 8.

P.S. You created great app! Thank you very much!

**Comment by johnno1962** [comment]
Use pacthed injection: Menu Item “macOS Project/ Patch App". You’ll need a main.m in your project.

**Comment by bonyadmitr** [comment]
Thanks!
