### ISSUE TITLE
run failure

### ISSUE THREAD

**Issue by zhaokera** [johnno1962/injectionforxcode#198]
ctrl+=

2017-01-25 10:30:36.193788 downPhoto[1661:39508] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/zhaok/Library/Developer/CoreSimulator/Devices/CF7EAFD0-2172-455F-A608-CA4820098DD9/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-01-25 10:30:36.194287 downPhoto[1661:39508] [MC] Reading from private effective user settings.

**Comment by johnno1962** [comment]
That’s a new one. Not sure it’s a problem with injection tho. Does it always do it?

**Comment by zhaokera** [comment]
yes,xcode8.2.1

**Comment by johnno1962** [comment]
Even with a simple example project? When did you download?

**Comment by zhaokera** [comment]
Today,runs successfully  but product->No menu

**Comment by johnno1962** [comment]
Are you using the plugin or the easier to use App? http://johnholdsworth.com/injection.html. There is no Product menu item with the App

**Comment by zhaokera** [comment]
ctrl+=
Compiling /Users/zhaok/downPhoto/downPhoto/downPhoto/main.m
        0.09 real         0.02 user         0.06 sys
2017-01-25 17:16:40.643 downPhoto[7895:417432] Injection Error: Could not locate referencesSection, are there any classes being injected?
2017-01-25 17:16:40.644 downPhoto[7895:417645] *** Bundle has failed to load. If this is due to symbols not found, this may be due to symbols being hidden from dynamic libraries. ***
10 injections performed so far.

**Comment by johnno1962** [comment]
You need to inject a Class file.

**Comment by zhaokera** [comment]
Injection app -> inject Source...->And then? 
 I am a rookie ,Can say in detail

**Comment by ccwinner** [comment]
@zhaokera The menu item doesn't show either in Product menu, how did you fix it?

**Comment by johnno1962** [comment]
The menu item in the product menu is only for the plugin version of injection. If you’re using the app http://johnholdsworth.com/injection.html it should appear on the task bar.

**Comment by ccwinner** [comment]
@johnno1962  I set up plugin first in reference of tutorial, and confirmed when Xcode reminded me of whether the plugin should be loaded. Then I closed the injection project, opened my own project in Xcode and failed to find the menu item in product menu.

**Comment by ansinyutin** [comment]
reinstalling the app helped me with this error:
Injection Error: Could not locate referencesSection, are there any classes being injected

**Comment by johnno1962** [comment]
Are you injecting a file that contains (non-generic) classes?

**Comment by johnno1962** [comment]
Did injection recompile this right file?

**Comment by ansinyutin** [comment]
After reinstalling the application, the injection recompiled the correct file. But after an hour of work, it's not. Now regardless of which file I try to recompile, it writes
** File not recently modified. Did you save it? **
Compiling .../WrongFileName.m

**Comment by johnno1962** [comment]
Are you using a “Companion Editor View”? Have you tried selecting the file in the file browser at the elft hand side?

**Comment by ansinyutin** [comment]
I had multiple tabs in Xcode. After I closed all the tabs everything worked. Thank you!
