### ISSUE TITLE
crash in this case

### ISSUE THREAD

**Issue by SilenceLee17** [johnno1962/injectionforxcode#201]
I have a view that contains an array called 'contentView' . Crash at [[self contentView] superview]

**Comment by johnno1962** [comment]
Are you using an -injected method? Best to rename the property if possible as the “sweep” for instances to notify uses this method name as well. Ohterwise you can use the INJECTION_BUNDLE_NOTIFICATION notification instead of instance level -injected.

**Comment by SilenceLee17** [comment]
Thx  : )
