### ISSUE TITLE
Automatic injection

### ISSUE THREAD

**Issue by bonyadmitr** [johnno1962/injectionforxcode#208]
HI, @johnno1962!
Does "Inject Source" available for automatic file changing and for launch?
It is for standalone Injection app.

**Comment by johnno1962** [comment]
Do you mean the file watcher? It’s available in the app version.

**Comment by bonyadmitr** [comment]
@johnno1962 
Great! It works!
File watcher work without patch but needs start Inject Source manually.
I tested it now and founded that automatically Inject Source start only for patched project. Is it true?

**Comment by johnno1962** [comment]
This is right
