### ISSUE TITLE
Seems not work on real device, Xcode8.2.1

### ISSUE THREAD

**Issue by FrizzleFur** [johnno1962/injectionforxcode#216]
Hi,  I want to test the injection on my iphone, I follow the  [patching_injection](https://github.com/johnno1962/injectionforxcode/blob/master/documentation/patching_injection.md), write the code in the main.m file,  the console shows the connecting is failed. 

`Injection attempting connection to: 10.12.1.67:31442`
`Injection: Could not connect: Connection refused`

My project is code in Objective-C, any suggestions?

**Comment by zenangst** [comment]
As of iOS 10, injection will no longer work when running the application on a device.
https://github.com/johnno1962/injectionforxcode#stop-stop-press

**Comment by FrizzleFur** [comment]
@zenangst  Well thanks~
