### ISSUE TITLE
Can injection use in Xcode 9 to develop iOS11?

### ISSUE THREAD

**Issue by Gh0stKnow** [johnno1962/injectionforxcode#221]
Can injection use in Xcode 9 to develop iOS11? 
Thx

**Comment by johnno1962** [comment]
There is a  separate version for Xcode 9 http://johnholdsworth.com/injection.html

**Comment by zenangst** [comment]
Works like a charm for me.

**Comment by Gh0stKnow** [comment]
Greatttt!
