### ISSUE TITLE
Support for whole module optimization

### ISSUE THREAD

**Issue by mgamer** [johnno1962/injectionforxcode#222]
Currently injectionforxcode only works if SWIFT_WHOLE_MODULE_OPTIMIZATION is disabled. Is support for whole module optimization technically possible? I'm asking because enabling whole module optimizations speeds up swift builds a lot.

**Comment by johnno1962** [comment]
Injection needs to ba able to build an individual file for it to work which is not possible parsing the logs when using WMO so I’m afraid it’s either or.

**Comment by johnno1962** [comment]
Having said that. You could try building you project without WMO once to set up the build logs which contain the compile commands. Then you can  building it with WMO if that’s your preference and trying injection to see if it works.
