### ISSUE TITLE
xcode9 can use it ?

### ISSUE THREAD

**Issue by liuaaaddxiaoer** [johnno1962/injectionforxcode#225]

**Comment by johnno1962** [comment]
Yes but you need to ensign your Xcode. There is a new app version though: http://johnholdsworth.com/injection.html

**Comment by polac24** [comment]
Remember also to set valid `xcode-select` path!

**Comment by rsardek** [comment]
I had problem with Xcode 9 and the previous versions of the Injection app, but the latest version of Injection does work great. Thank you.
