### ISSUE TITLE
Bundle build failed 

### ISSUE THREAD

**Issue by momoAI** [johnno1962/injectionforxcode#227]
injection console:

Useless use of numeric eq (==) in void context at /Users/pengxungui/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 619. buidRoot: /Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Build logDir: /Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Logs/Build  Use of uninitialized value $localBundle in substitution (s///) at /Users/pengxungui/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 156. Use of uninitialized value $localBinary in substitution (s///) at /Users/pengxungui/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 157. Use of uninitialized value $localBundle in concatenation (.) or string at /Users/pengxungui/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 160. Reference found where even-sized list expected at /Users/pengxungui/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 270. Learnt compile:     /Applications/Xcode_debug.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/pengxungui/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/pengxungui/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DCOCOAPODS=1 -DNDEBUG=1 -isysroot /Applications/Xcode_debug.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=7.0 -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Index/DataStore -iquote /Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Build/Intermediates.noindex/Foowwphone.build/Debug-iphonesimulator/Foowwphone.build/Foowwphone-generated-files.hmap -I/Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Build/Intermediates.noindex/Foowwphone.build/Debug-iphonesimulator/Foowwphone.build/Foowwphone-own-target-headers.hmap -I/Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Build/Intermediates.noindex/Foowwphone.build/Debug-iphonesimulator/Foowwphone.build/Foowwphone-all-target-headers.hmap -iquote /Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Build/Intermediates.noindex/Foowwphone.build/Debug-iphonesimulator/Foowwphone.build/Foowwphone-project-headers.hmap -iquotePods -iquotePods/AFNetworking -iquotePods/FMDB -iquotePods/Headers -iquotePods/Local\ Podspecs -iquotePods/Masonry -iquotePods/MJExtension -iquotePods/MJRefresh -iquotePods/PinYin4Objc -iquotePods/RegexKitLite -iquotePods/SDWebImage -iquotePods/Target\ Support\ Files -iquotePods/ZBarSDK -iquotePods/AFNetworking/AFNetworking -iquotePods/AFNetworking/UIKit+AFNetworking -iquotePods/FMDB/src -iquotePods/Headers/Private -iquotePods/Headers/Public -iquotePods/Masonry/Masonry -iquotePods/MJExtension/MJExtension -iquotePods/MJRefresh/MJRefresh -iquotePods/PinYin4Objc/PinYin4Objc -iquotePods/SDWebImage/SDWebImage -iquotePods/Target\ Support\ Files/AFNetworking -iquotePods/Target\ Support\ Files/FMDB -iquotePods/Target\ Support\ Files/Masonry -iquotePods/Target\ Support\ Files/MJExtension -iquotePods/Target\ Support\ Files/MJRefresh -iquotePods/Target\ Support\ Files/PinYin4Objc -iquotePods/Target\ Support\ Files/Pods-Foowwphone -iquotePods/Target\ Support\ Files/RegexKitLite -iquotePods/Target\ Support\ Files/SDWebImage -iquotePods/Target\ Support\ Files/ZBarSDK -iquotePods/ZBarSDK/include -iquotePods/ZBarSDK/iphone -iquotePods/ZBarSDK/zbar -iquotePods/FMDB/src/fmdb -iquotePods/Headers/Private/AFNetworking -iquotePods/Headers/Private/FMDB -iquotePods/Headers/Private/Masonry -iquotePods/Headers/Private/MJExtension -iquotePods/Headers/Private/MJRefresh -iquotePods/Headers/Private/PinYin4Objc -iquotePods/Headers/Private/RegexKitLite -iquotePods/Headers/Private/SDWebImage -iquotePods/Headers/Private/ZBarSDK -iquotePods/Headers/Public/AFNetworking -iquotePods/Headers/Public/FMDB -iquotePods/Headers/Public/Masonry -iquotePods/Headers/Public/MJExtension -iquotePods/Headers/Public/MJRefresh -iquotePods/Headers/Public/PinYin4Objc -iquotePods/Headers/Public/RegexKitLite -iquotePods/Headers/Public/SDWebImage -iquotePods/Headers/Public/ZBarSDK -iquotePods/MJRefresh/MJRefresh/Base -iquotePods/MJRefresh/MJRefresh/Custom -iquotePods/MJRefresh/MJRefresh/MJRefresh.bundle -iquotePods/PinYin4Objc/PinYin4Objc/Classes -iquotePods/PinYin4Objc/PinYin4Objc/Resources -iquotePods/ZBarSDK/include/zbar -iquotePods/ZBarSDK/iphone/include -iquotePods/ZBarSDK/iphone/res -iquotePods/ZBarSDK/zbar/decoder -iquotePods/ZBarSDK/zbar/processor -iquotePods/ZBarSDK/zbar/qrcode -iquotePods/ZBarSDK/zbar/video -iquotePods/ZBarSDK/zbar/window -iquotePods/MJRefresh/MJRefresh/Custom/Footer -iquotePods/MJRefresh/MJRefresh/Custom/Header -iquotePods/ZBarSDK/iphone/include/ZBarSDK -iquotePods/MJRefresh/MJRefresh/Custom/Footer/Auto -iquotePods/MJRefresh/MJRefresh/Custom/Footer/Back -I/Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Build/Products/Debug-iphonesimulator/include -I<Multiple -Ivalues> -I/Applications/Xcode_debug.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/libxml2 -I/Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Build/Intermediates.noindex/Foowwphone.build/Debug-iphonesimulator/Foowwphone.build/DerivedSources/x86_64 -I/Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Build/Intermediates.noindex/Foowwphone.build/Debug-iphonesimulator/Foowwphone.build/DerivedSources -Wno-shorten-64-to-32 -Wno-format -Wno-sometimes-uninitialized -F/Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Build/Products/Debug-iphonesimulator -F/Applications/Xcode_debug.app/Contents/Developer/Library/Frameworks -F/Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Foowwphone/Tencen -F/Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Foowwphone/Vender/BaiduMapSDK -F/Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1 -F/Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Foowwphone/Vender/JSPatch -isystem /Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Pods/Headers/Public -isystem /Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Pods/Headers/Public/AFNetworking -isystem /Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Pods/Headers/Public/FMDB -isystem /Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Pods/Headers/Public/MJExtension -isystem /Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Pods/Headers/Public/MJRefresh -isystem /Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Pods/Headers/Public/Masonry -isystem /Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Pods/Headers/Public/PinYin4Objc -isystem /Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Pods/Headers/Public/RegexKitLite -isystem /Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Pods/Headers/Public/SDWebImage -isystem /Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Pods/Headers/Public/ZBarSDK -include /Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Build/Intermediates.noindex/PrecompiledHeaders/Foowwphone-Prefix-cumowkxnjtvlrufnbqawjurspvkl/Foowwphone-Prefix.pch -MMD -MT dependencies -MF /Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Build/Intermediates.noindex/Foowwphone.build/Debug-iphonesimulator/Foowwphone.build/Objects-normal/x86_64/LoginViewController.d --serialize-diagnostics /Users/pengxungui/Library/Developer/Xcode/DerivedData/Foowwphone-cmgbfxbcjdcuoecbhyxwoscjhecs/Build/Intermediates.noindex/Foowwphone.build/Debug-iphonesimulator/Foowwphone.build/Objects-normal/x86_64/LoginViewController.dia -c /Users/pengxungui/Desktop/Branches/Foowwiphone_V4.2.1/Foowwphone/Main/Other/Login/LoginViewController.m -o iOSInjectionProject/x86_64/injecting_class.o sh: Multiple: No such file or directory  real	0m0.002s user	0m0.001s sys	0m0.001s  *** Learnt compile failed ***   at /Users/pengxungui/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 61. 	main::error('Learnt compile failed') called at /Users/pengxungui/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 437 *** Bundle build failed ***

**Comment by johnno1962** [comment]
-I<Multiple -Ivalues> ?

**Comment by polac24** [comment]
* What kind of Xcode do you use? 
* What **Import path** do you have in "Swift Compiler - Search Path" (*Build settings* of your `Foowwphone` target)? Does these search path depend on configuration)?

**Comment by momoAI** [comment]
My project search path went wrong， it work well when fixed
thanks for your help,the function is very powerful
