### ISSUE TITLE
Lazy Initialization won't be called

### ISSUE THREAD

**Issue by Hoikiiz** [johnno1962/injectionforxcode#230]
@property (weak, nonatomic) UITableView *tableView;

- (UITableView *)tableView
{
    if (_tableView == nil)
    {
        UITableView *tableView = [[UITableView alloc] initWithFrame:self.view.bounds style: UITableViewStylePlain];
        [self.view addSubview: tableView];
        tableView.backgroundColor = [UIColor orangeColor];
        _tableView = tableView;
    }
    return _tableView;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    [self tableView];
}

----------------------------------------------------

**Comment by johnno1962** [comment]
properties are not swizzled by injection.

**Comment by Hoikiiz** [comment]
Fine,thanks any way
