### ISSUE TITLE
xcode 9.2 crashed

### ISSUE THREAD

**Issue by cissusnar** [johnno1962/injectionforxcode#238]
Version 2.7 (655)

Exception Name: NSRangeException
Description: *** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray
User Info: (null)

0   CoreFoundation                      0x00007fff2b540fcb __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fff521e2c76 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff2b55b5ad -[__NSArray0 objectAtIndex:] + 93
3   Injection                           0x0000000100b5acd9 Injection + 724185
4   Injection                           0x0000000100b651a2 Injection + 766370
5   Injection                           0x0000000100b2301b Injection + 495643
6   Injection                           0x0000000100b229c8 Injection + 494024
7   Injection                           0x0000000100ab5394 Injection + 45972
8   Injection                           0x0000000100b22b30 Injection + 494384
9   Injection                           0x0000000100aad5ad Injection + 13741
10  libdispatch.dylib                   0x00007fff52d98d50 _dispatch_client_callout + 8
11  libdispatch.dylib                   0x00007fff52daf3f3 _dispatch_sync_thread_bound_invoke + 79
12  libdispatch.dylib                   0x00007fff52d98d50 _dispatch_client_callout + 8
13  libdispatch.dylib                   0x00007fff52da432d _dispatch_main_queue_callback_4CF + 1148
14  CoreFoundation                      0x00007fff2b4f9929 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
15  CoreFoundation                      0x00007fff2b4bbbea __CFRunLoopRun + 2586
16  CoreFoundation                      0x00007fff2b4baf43 CFRunLoopRunSpecific + 483
17  HIToolbox                           0x00007fff2a7d2e26 RunCurrentEventLoopInMode + 286
18  HIToolbox                           0x00007fff2a7d2b96 ReceiveNextEventCommon + 613
19  HIToolbox                           0x00007fff2a7d2914 _BlockUntilNextEventMatchingListInModeWithFilter + 64
20  AppKit                              0x00007fff28a9df5f _DPSNextEvent + 2085
21  AppKit                              0x00007fff29233b4c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
22  AppKit                              0x00007fff28a92d6d -[NSApplication run] + 764
23  AppKit                              0x00007fff28a61f1a NSApplicationMain + 804
24  Injection                           0x0000000100b15e69 Injection + 441961
25  libdyld.dylib                       0x00007fff52dd2115 start + 1
26  ???                                 0x0000000000000001 0x0 + 1

**Comment by johnno1962** [comment]
Have you tried the new Swift version of the app InjectionIII? http://johnholdsworth.com/injection.html

**Comment by cissusnar** [comment]
when I restart Xcode, It's never crashed again. 
I'll try new Swift version later. thank you
