### ISSUE TITLE
Animation is updating its progress with transitionCoordinator while it shouldn't ios10

### ISSUE THREAD

**Issue by denisPoifol** [johnno1962/injectionforxcode#239]
Hello I am having the following issue when I dismiss interactively a viewController the animation does not run but instead update itself with the transitionCoodinator or so it seems like it.
This only happen on iOS 10

this following testProject highlights the issue.
[LottieTest.zip](https://github.com/johnno1962/injectionforxcode/files/1825917/LottieTest.zip)

To test it you just have to press the button to present a new viewController and interactively dismiss it : on ios11 the loadingView do play the animation while on ios10 the animathie is progressing accordingly to the progress of the transition between viewControllers
We would expect it to behave like it does on iOS11 and play the animation as requested.

**Comment by johnno1962** [comment]
If it only happens on iOS 10 I’m not sure it’s problem with Injection itself.
