### ISSUE TITLE
Crash when inject source

### ISSUE THREAD

**Issue by demonliu** [johnno1962/injectionforxcode#246]
![image](https://user-images.githubusercontent.com/8512403/39964992-1040e598-56c3-11e8-810e-dffa03a39453.png)

Installed via Alcatraz, Xcode 9.2, Looking forward to your reply.

**Comment by johnno1962** [comment]
Could be any invalid pointer in your app. You won’t be able to use the injected() method to detect changes. Either try INJECTION_BUNDLE_NOTIFICATION instead or the new version “InjectionIII" in the mac app store.

**Comment by demonliu** [comment]
Thank you so much!

**Comment by demonliu** [comment]
Sorry, but i installed “InjectionIII" via app store, but there is no 'inject source' item . Although i followed the action in http://johnholdsworth.com/injection.html , it didn't work..
![image](https://user-images.githubusercontent.com/8512403/39982528-3ebd9640-5787-11e8-9c50-392603a032cb.png)

**Comment by johnno1962** [comment]
InjectionIII works differently from the previous versions. You need to add code to your application and then after you’ve selected the project all that should b required is to save the file for it to inject. Try the example app http://johnholdsworth.com/GettingStarted.zip to get you up and running.

**Comment by johnno1962** [comment]
Sorry there are a few versions of injection about but the one I’m trying to move people onto is the app store one. Once you have opened a project and added the required lines to your project all you should need to do is save the file and it should inject. control + = only works in the old versions of injection. There is a short video on the injection page: http://johnholdsworth.com/injection.html
