### ISSUE TITLE
Does it work with Swift 4?

### ISSUE THREAD

**Issue by dcb6** [johnno1962/injectionforxcode#247]
I've downloaded the app as well as performed several extra steps as outlined in this page to try to get it working: 

https://iosdevcenters.blogspot.com/2015/12/how-to-delete-derived-data-and-clean.html

Should this work with Swift 4? For me, when I press "ctrl + =" and xcode is in focus, nothing happens and I get the noise suggesting that this command does not do anything. I have made sure that Injection is running.

**Comment by johnno1962** [comment]
I’m not sure version you are using? Can you try the version in the Mac App Store please. It should work fine with Swift 4. http://johnholdsworth.com/injection.html

**Comment by dcb6** [comment]
Thanks for the reply, I got it working. I was following the instructions from the Github Readme rather than the link that you sent so I was missing the line of code that goes in AppDelegate.
