### ISSUE TITLE
Bundle creation fails if project is not in workspace directory

### ISSUE THREAD

**Issue by springsup** [johnno1962/injectionforxcode#25]
Bundle creation fails if the project is not in the workspace directory. For example, if I have a workspace MyApp, and two projects MyApp-Mac and MyApp-iOS in separate subfolders, it won't work.

I had a look in to this - it turns out the bundle creation script gets a workspace path in, and assumes that there is a project file in the same location with the same name as that workspace. If that isn't true (as it isn't in the case I described above), then it won't get the correct build settings (e.g. ARC enabled) and it won't be able to build the bundle.

see: [common.pm](https://github.com/johnno1962/injectionforxcode/blob/7c98556d0a8416512478995b056f5efb0a65b822/InjectionPluginLite/common.pm), [injectSource.pl](https://github.com/johnno1962/injectionforxcode/blob/7c98556d0a8416512478995b056f5efb0a65b822/InjectionPluginLite/injectSource.pl) (line 124)

**Comment by orta** [comment]
I'm ok with closing this, can't cover every use-case.
