### ISSUE TITLE
Lazy loading view does not work

### ISSUE THREAD

**Issue by shakesVan** [johnno1962/injectionforxcode#259]
this is my code:
```
class MYVC: UIViewController {
    
    lazy var btn: UIButton = {
        let btn = UIButton()
        btn.backgroundColor = UIColor.green
        //btn.backgroundColor = UIColor.blue
        return btn
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    func setupView() {
        view.addSubview(btn)
        //btn.backgroundColor = UIColor.red
        btn.frame = CGRect(x: 100, y: 100, width: 100, height: 100)
        
    }
}
```
then I set `btn.backgroundColor = UIColor.blue`,  it does not work in the closure . I want used the lazy-loding in the Injecttion , how to do this ?

**Comment by zenangst** [comment]
I'm guessing that you need a new instance of the button for it to work, as the instance variable is declared as `lazy`. 

@johnno1962 correct me if I'm wrong here :)

**Comment by shakesVan** [comment]
@zenangst I know what you say, but I can not at all in view viewDidLoad initialization, and I think it is unreasonable. These views should also be initialized when the controller is initialized, not in viewDidLoad. ViewDidLoad should only add views to self.view.

**Comment by shakesVan** [comment]
@zenangst Thanks very much, I fix it by this way:
```
class MYVC: UIViewController {
    
    var myView: MYView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        myView.data = "this is title"
    }
    
    func setupView() {
        myView = MYView()
        myView.backgroundColor = UIColor.red
        myView.layer.cornerRadius = 5
        view.addSubview(myView)
        myView.frame = CGRect(x: 50, y: 100, width: 300, height: 300)
        
    }
}
```
now, it's work when I change some thing in the `MYView` class.
then, I add this for fix `command` + `s` don't work in a `UIView` class
```
extension UIView {
    #if DEBUG
    @objc func injected() {
        print("injected UIView")
        guard let lastVC = UIApplication.shared.keyWindow?.rootViewController else {
            return
        }
        
        for subV in lastVC.view.subviews {
            subV.removeFromSuperview()
        }
        lastVC.viewDidLoad()
    }
    #endif
}
```

**Comment by zenangst** [comment]
@shakesVan awesome, super nice that you were able to solve it :)

**Comment by zenangst** [comment]
Injection only works in the simulator due to changes in iOS sandboxing.

Reference: https://github.com/johnno1962/injectionforxcode/issues/202

**Comment by shakesVan** [comment]
@zenangst Thanks
