### ISSUE TITLE
It's(InjectionIII Version 1.2 (1155)) not work for xcode10 (10A255)

### ISSUE THREAD

**Issue by xuhongfei** [johnno1962/injectionforxcode#263]
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Reason: image not found

also

Open Project  -> Select Project Directory         nothing to do

**Comment by donirn** [comment]
Hi @xuhongfei , I'm trying to help, you can just download the new Injection app meant for XCode 10. Here is the link to direct download http://johnholdsworth.com/InjectionX.app.zip

**Comment by xuhongfei** [comment]
THX
