### ISSUE TITLE
Error loading, Can't work on Xcode 10, Mojave.

### ISSUE THREAD

**Issue by VisualEcho** [johnno1962/injectionforxcode#264]
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265)

I used Xcode 10, Mojave.

I have download a version for Xcode 10, but it doesn't work.

**Comment by johnno1962** [comment]
You need the new version downloadable from http://johnholdsworth.com/InjectionIII.app.zip or wait a few days for the new version to make it to the App Store. If you have already downloaded it, in what way doesn’t work. Is it giving any error message?

**Comment by VisualEcho** [comment]
Yeap, I downloaded this new version and tried again. 
The error message:

2018-09-30 16:44:58.293290+0800 newUIFeature[16607:772619] Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Symbol not found: __T0BOWV
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Expected in: /Users/chenxiang/Library/Developer/CoreSimulator/Devices/A3E82847-3CA9-4114-8B09-6C31874A1060/data/Containers/Bundle/Application/DDC4EAD0-335F-4826-B6B8-FA6E4CDEDD1A/newUIFeature.app/Frameworks/libswiftCore.dylib
 in /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection

**Comment by johnno1962** [comment]
Did you change the path in your AppDelegate to /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle ?

**Comment by VisualEcho** [comment]
OK, got it , I still used the path "/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle"
It works now. Thank you very much.
