### ISSUE TITLE
fatal error: 'header.h' file not found #import "header.h"

### ISSUE THREAD

**Issue by amit115** [johnno1962/injectionforxcode#266]
I have folder structure as following in my app : 
Base/privateFolder/header.h
Base/AppFolder/Appcode.m

In the Appcode.m i am calling the #import "header.h" .The plugin is not able to find the header.h file and recompilation fails.If i keep the .h file in the same folder as Appcode.m it is able to find it but this is not possible as i have a well structured huge code base .
How could i overcome this issue?

**Comment by iceYou123** [comment]
+1 help

**Comment by johnno1962** [comment]
You could add the path to your project’s header include path perhaps?
