### ISSUE TITLE
work fine on GettingStarted,  but not work on my project? look forward to your resolution.

### ISSUE THREAD

**Issue by amjunliang** [johnno1962/injectionforxcode#268]
*** Compiling /Users/pony/Example/ExampleUniversal/AppDelegate.m ***
*** Re-compilation failed (/Users/pony/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
fatal error: malformed or corrupted AST file: 'could not find file '/Users/pony/Example/Classes/Common/UIKit/Views/ZYActionSheet.h' referenced by AST file '/Users/pony/Library/Developer/Xcode/DerivedData/ExampleUniversal-fqwtlfdynkpnbhclekthvimgvnmq/Build/Intermediates.noindex/PrecompiledHeaders/ExampleUniversal-Prefix-doczfcubvmerjccrdhofhcqzzwzv/ExampleUniversal-Prefix.pch.pch''
note: after modifying system headers, please delete the module cache at '/Users/pony/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/17WCCRMBPW24M'
1 error generated.
 ***

 *** Compiling /Users/pony/Example/Classes/Pasteboard/Controller/ZYAladdinMessageDialogController.swift ***
*** Re-compilation failed (/Users/pony/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
<unknown>:0: error: error opening input file '/Users/pony/Example/Classes/Common/UIKit/Views/ZYSegmentView.swift' (No such file or directory)
 ***

**Comment by remlove** [comment]
i met the same issue.need help...

**Comment by johnno1962** [comment]
This probably because you have space or bracket () characters in your project path
