### ISSUE TITLE
Remove completely

### ISSUE THREAD

**Issue by vbklv** [johnno1962/injectionforxcode#273]
How can injection 2.x, installed several Xcode versions ago, be removed completely ?

**Comment by johnno1962** [comment]
Hi, If it’s an app you can just remove the app. If it was one of the plugin versions you can remove ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin

**Comment by vbklv** [comment]
I removed the app but there is still an Inject in the action menu for each file in Finder, and there is no Developer folder in Application Support :)

**Comment by johnno1962** [comment]
Hmmm. Googling around the command seems to be:
killall pbs;/System/Library/CoreServices/pbs -flush

**Comment by vbklv** [comment]
It’s gone from file action menu, thanks!

**Comment by johnno1962** [comment]
👍
