### ISSUE TITLE
It seems not work on simulator，Xcode 10.1

### ISSUE THREAD

**Issue by Jerry4me** [johnno1962/injectionforxcode#274]
Simulator：iPhone 6s 10.3.1
Xcode：Xcode 10.1(10B61)

Error Message:

Loading .dylib - Ignore any duplicate class warning...
*** dlopen() error: dlopen(/Users/xudequan/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval102.dylib, 2): Symbol not found: ___llvm_profile_runtime
  Referenced from: /Users/xudequan/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval102.dylib
  Expected in: flat namespace
 in /Users/xudequan/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval102.dylib ***

**Comment by Jerry4me** [comment]
> Hi, this is due to collecting test coverage data. Please turn it off in your project scheme.

Thanks !!!

**Comment by teameh** [comment]
Hi @johnno1962 I'm still running into this problem even when coverage is turned off.. 

``
💉 *** Compiling /Users/veen011/Projects/Apps/MyProject/MenuViewController.swift ***
💉 Loading .dylib - Ignore any duplicate class warning...
💉 *** dlopen() error: dlopen(/Users/veen011/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib, 2): Symbol not found: ___llvm_profile_runtime
  Referenced from: /Users/veen011/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib
  Expected in: flat namespace
 in /Users/veen011/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib ***
```

Using v1.4 from the AppStore and this in my AppDelegate: 

```
    Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle")!.load()
```

Your GettingStarted Project works fine though..

**Comment by johnno1962** [comment]
Sounds like you need to clean and rebuild your project from scratch.

**Comment by frowing** [comment]
@johnno1962 Hitting the same issue. Cleaning and rebuilding from scratch did not work. Any other ideas?
