### ISSUE TITLE
Error loading, Can't work on Xcode 10.1, Mojave. 

### ISSUE THREAD

**Issue by FKLam** [johnno1962/injectionforxcode#276]
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Symbol not found: __T0BOWV
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Expected in: /Users/amglfk/Library/Developer/CoreSimulator/Devices/4020260E-EFF1-4502-A107-B6176818930D/data/Containers/Bundle/Application/B97304C7-EDC0-46BA-9E21-CB27B756F241/WarmWaterBag.app/Frameworks/libswiftCore.dylib
 in /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection

My project has used Swift

**Comment by johnno1962** [comment]
Hi, with Xcode 10.1 you need to load _/Applications/InjectionIII.app/Contents/Resources/iOSInjection10_

**Comment by FKLam** [comment]
> Hi, with Xcode 10.1 you need to load _/Applications/InjectionIII.app/Contents/Resources/iOSInjection10_

Thx,
