### ISSUE TITLE
Re-compilation failed ,but delete the `DerivedData ` files , still  fail 

### ISSUE THREAD

**Issue by WangGuibin** [johnno1962/injectionforxcode#278]
💉 *** Re-compilation failed (/Users/wangguibin/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
fatal error: malformed or corrupted AST file: 'could not find file '/Users/wangguibin/Desktop/MonoEnglishParty/MonoEnglishParty/iflyMSC.framework/Headers/iflyMSC.h' referenced by AST file '/Users/wangguibin/Library/Developer/Xcode/DerivedData/MonoEnglishParty-bgkhpxyvjymolpepaevvdmycmhgs/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/3526394885614652269/PrefixHeader.pch.gch''
note: after modifying system headers, please delete the module cache at '/Users/wangguibin/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1AZAIBO4U0LXV'
1 error generated.

**Comment by su350380433** [comment]
你是用了cocoapod的吗？ 我的也是出现了找不到PrefixHeader.pch.gch

**Comment by WangGuibin** [comment]
> 你是用了cocoapod的吗？ 我的也是出现了找不到PrefixHeader.pch.gch

是的 写个简单的demo是可以的 放到自己项目里的时候不行,全局的头文件引用太多了, 压根理不清~   然后这个东西目前只支持模拟器的热重载 , 所以没深入去研究这个问题了, 这个issue我关了

**Comment by remlove** [comment]
我查了半天也没找到解决的办法

**Comment by songxing10000** [comment]
Say where you can't find pch, just put the copy of pch where
