### ISSUE TITLE
It seems not work on simulator，Xcode 10.2

### ISSUE THREAD

**Issue by kuwo0322** [johnno1962/injectionforxcode#281]
/Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10, 265): Symbol not found: _$SBOWV
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib
 in /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10

**Comment by johnno1962** [comment]
Hi, With Xcode 10.2.1 you use iOSInjection.bundle instead of iOSInjection10.bundle

**Comment by kuwo0322** [comment]
Injection connected, But still not work.What should I do？
 *** Could not locate containing project or it's logs.
On macOS you need to turn off the App Sandbox.
Have you customised the DerivedData path? ***

**Comment by johnno1962** [comment]
Do you have non-ascii characters in the path to your project?

**Comment by kuwo0322** [comment]
"/Users/jianghg/Documents/practice/Explore/InjectionTest/InjectionTest" is my project path

**Comment by johnno1962** [comment]
Are you using custom "Derived Data" path?

**Comment by kuwo0322** [comment]
I use defalult "Derived Data" path instead of custom  path and it works now. thanks very much!
