### ISSUE TITLE
InjectionX.app Not work 

### ISSUE THREAD

**Issue by WangGuibin** [johnno1962/injectionforxcode#282]
Error loading /Applications/InjectionX.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionX.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Symbol not found: _$SBOWV
  Referenced from: /Applications/InjectionX.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib
 in /Applications/InjectionX.app/Contents/Resources/iOSInjection.bundle/iOSInjection

**Comment by WangGuibin** [comment]
Xcode   Version 10.1 (10B61)

**Comment by johnno1962** [comment]
Hi, for Xcode 10.1 you need to load /Applications/InjectionX.app/Contents/Resources/iOSInjection10.bundle

**Comment by WangGuibin** [comment]
This is a pit dug by myself.   I installed two versions of Xcode and changed the name, which means the path has changed, so I can't link it.
```
xcode-select -print-path
/Applications/Xcode10.1.app/Contents/Developer
```
I am now back. rename `Xcode 10.1.app` => `Xcode.app` ,then 
```
sudo xcode-select -switch  /Applications/Xcode.app/Contents/Developer
```
The world is getting better~  Still the previous code can run
```objc
#if DEBUG
    //UI hot reload
    [[NSBundle bundleWithPath:@"/Applications/InjectionX.app/Contents/Resources/iOSInjection.bundle"] load];
#endif    

```

**Comment by johnno1962** [comment]
Where are you getting InjectionX.app from? The supported version is InjectionIII in the mac App Store.

**Comment by WangGuibin** [comment]
The souce from network ，link for https://www.jianshu.com/p/a049fa394575

**Comment by johnno1962** [comment]
That is a very old version and not the primary source. Please use InjrectionIII from the Mac App Store. It's free.

**Comment by WangGuibin** [comment]
OK ! I really appreciate the open source spirit of the author~ I will change the latest one immediately.
