### ISSUE TITLE
error: open /~/bin/unhide.sh: No such file or directory

### ISSUE THREAD

**Issue by huangzhentong** [johnno1962/injectionforxcode#283]
PBXCp /Users/kt-stc08/Downloads/injectionforxcode-master/InjectionPluginLite/unhide/unhide.sh /~/bin/unhide.sh (in target: unhide)
    cd /Users/kt-stc08/Downloads/injectionforxcode-master/InjectionPluginLite/unhide
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/kt-stc08/Downloads/injectionforxcode-master/InjectionPluginLite/unhide/unhide.sh /\~/bin

error: open /~/bin/unhide.sh: No such file or directory

**Comment by johnno1962** [comment]
This repo is not the current version of injection which is `InjectionIII` in the Mac App Store.

**Comment by huangzhentong** [comment]
Thanks

> 在 2019年7月30日，下午4:59，John Holdsworth <notifications@github.com> 写道：
> 
> InjectionIII
