### ISSUE TITLE
💉 *** Re-compilation failed. (When multiple projects exist in workspace.)

### ISSUE THREAD

**Issue by 1357594445** [johnno1962/injectionforxcode#284]
💉 *** Re-compilation failed (/Users/administrator/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
In file included from /Users/administrator/Desktop/xxx/VVMeAccountViewController.m:11: fatal error: 'BaseViewController.h' file not found
#import "BaseViewController.h"

VVMeAccountViewController.m is in xxx.project.
BaseViewController.h is in RootLib.project.

**Comment by johnno1962** [comment]
Hi, I’m sorry but this isn’t supported.

**Comment by hashem-intelligentb** [comment]
I got this error:
```
💉 *** Compiling /Users/hashemabounajmi/Documents/Xcode Projects/MyApp/SlideMenu/Profile/UpdateProfile/UpdateProfileViewController.swift ***

💉 *** Re-compilation failed (/Users/hashem/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
<unknown>:0: error: error opening input file '/Users/hashem/Documents/Xcode Projects/MyApp/SlideMenu/Settings/SettingsInteractor.swift' (No such file or directory)
 ***
```

any idea? I checked, file exists at that directory.

**Comment by johnno1962** [comment]
This is probably sue to a difference between cpp/lower case in the project and the actual file. Check the file /Users/hashem/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh

**Comment by hashem-intelligentb** [comment]
Thanks for quick answer, may you explain more or what should I do to solve this?
I opened the command.sh file, it's a verbose file!

**Comment by johnno1962** [comment]
You need to check the name of the file on the disk is exactly the same as the path in the command.sh. `Viewcontroller.swift` and `ViewController.swift` are not the same for injection.

**Comment by DaiyiLL** [comment]
the same issue:
error opening input file '/Users/mac/Desktop/iOS_PRJ/GitCode/Photo/LittleMan/LIttleMan/Classes/Main/Friends/Views/LMHTMLCell.swift' (No such file or directory)

**Comment by johnno1962** [comment]
Hi, If this is the App Store version of InjectionIII this is probably to do with case sensitivity. Please try one of the GitHub releases if you haven't already.
