### ISSUE TITLE
Hello, do you still support dynamic debugging of storyboard (without compiling) and opening the color version? I downloaded it from appstore

### ISSUE THREAD

**Issue by zuqiu123** [johnno1962/injectionforxcode#287]
Hello, do you still support dynamic debugging of storyboard (without compiling) and opening the color version? I downloaded it from appstore
<img width="949" alt="d" src="https://user-images.githubusercontent.com/15611129/66377974-293a9b00-e9e5-11e9-8a46-57e203f2f149.png">

Does the appstrore version also support two features?

**Comment by johnno1962** [comment]
Hi, you’re looking at the old repo from the look of things. The App in the App Store `InjectionIII` supports limited injection of Storyboards if you build them while the App is running and connected. It should reload the currently displayed view controller. Note: you don’t save the storyboard but build your app instead.

**Comment by zuqiu123** [comment]
I can understand that every time I change Storyboards, I have to use command + B before he will take effect. Is it true that the real-time display is not supported without compiling? Is this correct?

**Comment by johnno1962** [comment]
That’s right, you need to build storyboards to have them inject.

**Comment by zuqiu123** [comment]
Thank you, thank you for your work, great.

**Comment by zuqiu123** [comment]
Hello, I am having a problem with debugging. How do I change the collview delegate method?
- (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath

I don't know how to pass in parameters
- (void)injected{
     [self collectionView:self.actionCollectionView layout:0 sizeForItemAtIndexPath:0];
}

Can you help me, thank you

**Comment by zuqiu123** [comment]
Great God, can you post a new tutorial video on YouTube?

**Comment by johnno1962** [comment]
You asked a question about code not related to InjectionIII. How am I supposed to know what your collection view delegate arguments should be! Perhaps you could store them somewhere.

**Comment by zuqiu123** [comment]
Hello idol，If I want to modify viewDidLoad, I call the registration method and write it in the registration method, because viewDidLoad has no parameters, so I call it and I can modify the code in viewDidLoad dynamically.
`  
@objc func injected() {
        viewDidLoad()
  }
`

But some code is in dalegate. I want to dynamically modify the code in these methods, such as setting the color of the cell.
`
  func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell:FaceCellCollectionViewCell = collectionView.dequeueReusableCell(withReuseIdentifier: cell_ID, for: indexPath) as! FaceCellCollectionViewCell
        cell.backgroundColor = .white
        return cell
    }
`
 I don’t know how to write in injected to change color to red
`
@objc func injected () {
// i don't know how to write
}
`
I look forward to your answer
