### ISSUE TITLE
Crashes when saving using objective-c app

### ISSUE THREAD

**Issue by GabeJacobs** [johnno1962/injectionforxcode#294]
` 💉 *** Compiling /Users/gabejacobs/Desktop/Fart World/Fart World/FFFCreateViewController.m ***
💉 Loading .dylib ...
objc[31805]: Class FFFCreateViewController is implemented in both /Users/gabejacobs/Library/Developer/CoreSimulator/Devices/CDB51A4A-667B-43E1-B043-454806D437D3/data/Containers/Bundle/Application/9E579D7C-32F2-4FEE-984E-28F380962CB4/Fart World.app/Fart World (0x10d14df28) and /Users/gabejacobs/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib (0x11aed40e8). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning ^
(lldb) 
`

Don't mind the app name, haha

**Comment by johnno1962** [comment]
Do you have an injected() method? If so, try using “INJECTION_BUNLE_NOTIFICATION” notification.

**Comment by GabeJacobs** [comment]
@johnno1962 that did it, thank you. Such an amazing tool... can't believe how much time I have wasted recompiling
