### ISSUE TITLE
Error loading iOSInjection.bundle

### ISSUE THREAD

**Issue by RQ0588** [johnno1962/injectionforxcode#296]
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection, 265): Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle/iOSInjection
  Reason: image not found

xcode 11.3.1 (11C504)

**Comment by johnno1962** [comment]
HI, Is this the App Store version? Do you have your Xcode at the standard path `/Applications/Xcode.app`

**Comment by RQ0588** [comment]
> HI, Is this the App Store version? Do you have your Xcode at the standard path `/Applications/Xcode.app`

Xcode Version 11.6 (11E708)  no problems.
