### ISSUE TITLE
Error reading 

### ISSUE THREAD

**Issue by Free-am** [johnno1962/injectionforxcode#298]
💉 Injection connected 👍
💉 Watching /Users/xx/Desktop/xx/xxxx/**

💉 *** Error reading /var/folders/j0/k_wwqqls2mgbv10m1tkrh2b40000gn/T/com.johnholdsworth.InjectionIII/eval104.sh, scanCommand: /var/folders/j0/k_wwqqls2mgbv10m1tkrh2b40000gn/T/com.johnholdsworth.InjectionIII/command.sh ***

**Comment by johnno1962** [comment]
Hi, this is often because people have their project in the Desktop folder. Can you move the project to another folder?
