### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by pengzhiqiang110** [johnno1962/injectionforxcode#299]
/Users/pd1/Desktop/xld-ios/Salarie/Salarie/Manifest/Salarie-Bridging-Header.h:38:
#import <BaiduMapAPI_Search/BMKSearchComponent.h>//引入检索功能所有的头文件
/Users/pd1/Desktop/xld-ios/Salarie/Pods/BaiduMapKit_Subspec/BaiduMapKit/BaiduMapAPI_Search.framework/Headers/BMKSearchComponent.h:14:9: error: 'BMKPOISearchResult.h' file not found
#import "BMKPOISearchResult.h"
        ^
<unknown>:0: error: failed to import bridging header '/Users/pd1/Desktop/xld-ios/Salarie/Salarie/Manifest/Salarie-Bridging-Header.h'
 ***
报这个错是什么原因,这个工具可以在oc和swifte混编环境运行吗

**Comment by johnno1962** [comment]
你好。 是的，但是不要使用〜/ Desktop文件夹
