### ISSUE TITLE
这个东西是不是不支持 swift和oc混编项目

### ISSUE THREAD

**Issue by pengzhiqiang120** [johnno1962/injectionforxcode#300]
💉 *** Compiling /Users/pd1/Desktop/xld-ios/Salarie/Salarie/Controller/Home/UI/HomeOneCell.swift ***
💉 *** Re-compilation failed (see: /var/folders/7n/hw7q2mjn4fz5_ksxh_40p9g80000gn/T/com.johnholdsworth.InjectionIII/command.sh)
/Users/pd1/Desktop/xld-ios/Salarie/Salarie/Manifest/Salarie-Bridging-Header.h:38:9: note: in file included from /Users/pd1/Desktop/xld-ios/Salarie/Salarie/Manifest/Salarie-Bridging-Header.h:38:
#import <BaiduMapAPI_Search/BMKSearchComponent.h>//引入检索功能所有的头文件
/Users/pd1/Desktop/xld-ios/Salarie/Pods/BaiduMapKit_Subspec/BaiduMapKit/BaiduMapAPI_Search.framework/Headers/BMKSearchComponent.h:14:9: error: 'BMKPOISearchResult.h' file not found
#import "BMKPOISearchResult.h"
        ^
<unknown>:0: error: failed to import bridging header '/Users/pd1/Desktop/xld-ios/Salarie/Salarie/Manifest/Salarie-Bridging-Header.h'
💉 ⚠️ Adjust the "Header Search Paths" in your project's Build Settings ***
报这个错误怎么去解决

**Comment by johnno1962** [comment]
Please see https://github.com/johnno1962/HotReloading/issues/11#issuecomment-818549785 where we are looking at this problem. It may help to download one of the un-sandboxed releases https://github.com/johnno1962/InjectionIII/releases/tag/2.6.6 if this is related to "case sensitivity"
