### ISSUE TITLE
is support m1 mac?

### ISSUE THREAD

**Issue by gaoyuqiang** [johnno1962/injectionforxcode#302]
now does it support m1?

**Comment by johnno1962** [comment]
Absolutely.

**Comment by gaoyuqiang** [comment]
> Absolutely.

because m1 mac‘s simulator run arm64,  does it still work? ^_^    I prepare to buy one m1 mac

**Comment by johnno1962** [comment]
I have an m1 mac! Buy one, you won't regret it.

**Comment by gaoyuqiang** [comment]
so can it work on m1 mac's arm64 simulator?  (I love injection and love hot-reload)

**Comment by johnno1962** [comment]
Yes. InjectionIII has been built multiple-architecture for a year now.
