### ISSUE TITLE
Experiencing Crash in XCode 6

### ISSUE THREAD

**Issue by ben95beng** [johnno1962/injectionforxcode#37]
I just installed this app and I am testing it. When I am running my application and I click on Xproble -> load, the app crashes. Console output shows:

Injection attempting connection to: 127.0.0.1:31442
Injection: Could not connect: Connection refused
Xprobe: Connecting to 127.0.0.1
Xprobe: sweeping memory, filtering by ''

- Why is it unable to connect. Is there a way to fix this?

**Comment by johnno1962** [comment]
Hi,

Have you synced recently? I may have pushed the solution to this problem.

John
  ----- Original Message ----- 
  From: ben95beng 
  To: johnno1962/injectionforxcode 
  Sent: Friday, February 06, 2015 5:35 AM
  Subject: [injectionforxcode] Experiencing Crash in XCode 6 (#37)


  I just installed this app and I am testing it. When I am running my application and I click on Xproble -> load, the app crashes. Console output shows:

  Injection attempting connection to: 127.0.0.1:31442
  Injection: Could not connect: Connection refused
  Xprobe: Connecting to 127.0.0.1
  Xprobe: sweeping memory, filtering by ''

    a.. Why is it unable to connect. Is there a way to fix this?

**Comment by ben95beng** [comment]
Hi John,
I installed the app 3 days ago. Do I need to sync and how?

**Comment by johnno1962** [comment]
Ignore the “Injection: Could not Connect”, Xprobe itself seems to have connected what are you seeing?

**Comment by ben95beng** [comment]
- Here is the console output. When I tried it this time, it did not crash. I had done 'Update Plugins' in the injection plugin menu. My question is: will I be able to inject code when the connection is failing?

+[BundleInjection load] 127.0.0.1 (see project's main.(m|mm)
Xprobe: Connecting to 127.0.0.1
Injection attempting connection to: 127.0.0.1:31442
Injection: Could not connect: Connection refused
Xprobe: sweeping memory, filtering by ''
Xprobe: sweep complete, 300 objects found
Injection attempting connection to: 127.0.0.1:31442
Injection: Could not connect: Connection refused
Injection attempting connection to: 127.0.0.1:31442
Injection: Could not connect: Connection refused
Giving up on connecting to Injection

**Comment by johnno1962** [comment]
Your Xprobe looks ok. Can you see the Injection options on the product menu i.e. is the injection plugin loaded? Xprobe and Injection are separate plugins. Also is the Xocde 6.2, Injection will not load on Xcode 6.2. Try building injection from github.

**Comment by ben95beng** [comment]
Yes, Xcode is 6.2. I do not see an Injection option in Product menu.

**Comment by johnno1962** [comment]
Sync injection and rebuild and it should load, I’ve updated the UUID for 6.2

**Comment by ben95beng** [comment]
How do I sync Injection? Is it the 'Update Plugins' menu in the Injection Plugin?

**Comment by johnno1962** [comment]
Yes, that should work but you are better building from github sources.

**Comment by ben95beng** [comment]
Ok, thanks. I will try it.
