### ISSUE TITLE
Slow injection

### ISSUE THREAD

**Issue by mgamer** [johnno1962/injectionforxcode#39]
I just installed latest version and it seems to be way slower than before. I tracked down the problem to be in this line in `injectSource.pl`:
```
my %VARS = `$xcodebuild -showBuildSettings $config` =~ /    (\w+) = (.*)\n/g;
```

On empty project on my MacBookPro Retina 2012 it takes 1.6 s to just execute `xcodebuild -showBuildSettings` so it's kind of slow for injection.

I noticed that in `injectSource.pl` there's a check if the file injection.txt already exists but I also noticed that identity.txt is explicitly removed later on in line 150 `unlink $infoFile if !-d $localBundle;`.

Due to my limited knowledge of Perl I can only guess but it looks like identity.txt is only deleted when if `$localBundle` is defined. 

Is it possible the there's some bug around removing that identity.txt file?

**Comment by johnno1962** [comment]
Hi Michał. I’ve just checked and I’m not seeing this problem this end building from github.

Parsing the build parameters using "xcodebuild -showBuildSettings” should only happen once however and the problem must be that the directory $localBundle does not exist (-d) (have you changed your Xcode "Locations” preferences?) which is causing the $infoFile to be deleted.

Injection is in code freeze at the moment as it currently being re-written in Swift (yay) so I’m unlikely to push out a fix just now. For now I would comment out line 150 and you should be fine. I’ll let you know when the new Beta version of injection is ready to download if you want to “kick the tires”.

**Comment by mgamer** [comment]
Hi John,

thanks for your answer. Good luck with the Swift implementation! 

I've debugged the problem at bit more and it looks like `$buildRoot` is not defined which probably is because I'm running injection from AppCode plugin. I'll check more later and let you know what I come up with. I'm looking at the AppCode plugin eitherway because I would like to make it be able to automatically run the app if it is not running. So that I don't need to separately run the app and inject the code. I would love to make it work with the same key. BTW Does it sound to you like a good idea?

**Comment by johnno1962** [comment]
Using with AppCode is a case $buildRoot is not defined so I’ve pushed a small change to stop the $infoFile from being deleted all the time.

$infohttps://github.com/johnno1962/injectionforxcode/commit/3a04899f50cb6743a5d801c2dbc417ba7a9c4188. 

Could you download the latest version and check and let me know if this is fixed?

**Comment by zintus** [comment]
This issue happens for me too, using latest versions of injection and AppCode. I've generated info file once, and commented line deleting file afterwards. Now injected is fast again.

How could i help to fix this issue for everyone?

**Comment by johnno1962** [comment]
$buildRoot shouldn’t be defined when using AppCode so it shouldn’t remove the file. Can you look at whethere $buildRoot is defined?
