### ISSUE TITLE
why I have a codesign error?

### ISSUE THREAD

**Issue by ChenWuLin** [johnno1962/injectionforxcode#40]
** RECORDED BUILD SUCCEEDED **

Renaming bundle so it reloads..
rm -rf "/Users/starcwl/Desktop/viewHier/iOSInjectionProject/build/Debug-iphoneos/InjectionBundle3.bundle" && cp -r "/Users/starcwl/Desktop/viewHier/iOSInjectionProject/build/Debug-iphoneos/InjectionBundle.bundle" "/Users/starcwl/Desktop/viewHier/iOSInjectionProject/build/Debug-iphoneos/InjectionBundle3.bundle"
Codesigning with identity 'iPhone Developer' for iOS device
iPhone Developer: ambiguous (matches "iPhone Developer: WuLin Chen (FZAT3C2YZ5)" and "iPhone Developer: WuLin Chen (FZAT3C2YZ5)" in /Users/starcwl/Library/Keychains/login.keychain)
Could not codesign as 'iPhone Developer': /Users/starcwl/Desktop/viewHier/iOSInjectionProject/build/Debug-iphoneos/InjectionBundle3.bundle at /Users/starcwl/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 51.
main::error('Could not codesign as 9hone Developerø/Users/starcwl/De...') called at /Users/starcwl/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 422
*** Bundle build failed ***
Check Bundle project.

all these two project build success, but can't inject code to my device.

enviroment: iPhone5s XCode6.2

simulator works fine.

**Comment by johnno1962** [comment]
iPhone Developer: ambiguous (matches "iPhone Developer: WuLin Chen (FZAT3C2YZ5)" and "iPhone Developer: WuLin Chen (FZAT3C2YZ5)" in /Users/starcwl/Library/Keychains/login.keychain)

you seem to have a duplicate in your keychain under the identifier “iPhone Developer"
