### ISSUE TITLE
Cannot load nif file

### ISSUE THREAD

**Issue by haxpor** [johnno1962/injectionforxcode#42]
I've built the project from github.
It's successfully built, but when I start Xcode it shows the error below.

![screen shot 2015-05-22 at 12 35 37 am](https://cloud.githubusercontent.com/assets/673757/7755034/72840048-001b-11e5-98f0-476bf1a139ca.png)

I can see Injectcode option under Product menu, but when I click on it, it has no effect like it does nothing.

I use Xcode 6.3.2 (6D2105).

**Comment by johnno1962** [comment]
Did you do a build clean?

**Comment by haxpor** [comment]
Works now.
