### ISSUE TITLE
Does it try to call a method on the injected object?

### ISSUE THREAD

**Issue by olegam** [johnno1962/injectionforxcode#45]
Until now I have been using dyci (https://github.com/DyCI/dyci-main/) for code injection. After injecting the new class implementation dyci will call the method `-(void)updateOnClassInjection` on instances of the class. This let's me recursively rebuild the UI.

Does injectionsforxcode have a similar method it will call on instances after injection? Or is it something we could add? If so it would be great if it was called the same as the dyci method for compability:)

**Comment by olegam** [comment]
.. and I forgot to menthion the reason I'm really excited about this project is the Swift support!

**Comment by bolismauro** [comment]
+1
I'm interested in it too

**Comment by johnno1962** [comment]
Thinking about it.. not easy. dicy swizzles -[NSObject init] to do this which I’m not keen to do.

**Comment by johnno1962** [comment]
This long awaited feature to call -injected on objects should work now. Let me know it there are any problems.

**Comment by olegam** [comment]
Thanks! I will test it out as soon as I have a chance.

**Comment by bolismauro** [comment]
I'm currently working on something else.
I will give it a shoot as soon as possible.
Thanks!
