### ISSUE TITLE
error: use of '@import' when modules are disabled 

### ISSUE THREAD

**Issue by mcplectrum** [johnno1962/injectionforxcode#46]
Hi,
is there a way to get injection working, while using modules? It is working for me when i do not use modules and i love to use this plugin and would like to use it in a project with tons of @import's. 

I have set Enable Modules (C and Objective-C) to yes, for all of my target but i get:
  
    error: use of '@import' when modules are disabled 

It is the same error for unpatched and patched projects.

**Comment by johnno1962** [comment]
Hi, I’ve seen this but can’t replicate it just at the moment. Is this an error in compiling or linking? One theing you can try is to enable modules in the “Bundle Project” (Product/Project/Open Bundle Project)

**Comment by mcplectrum** [comment]
Thank you for your fast reply. It is now also working with modules, after i enabled them in the "Bundle Project", as you have described above. 

Is the -fmodules missing for the "Bundle Project"?
