### ISSUE TITLE
Inject source failed for Swift

### ISSUE THREAD

**Issue by hyouuu** [johnno1962/injectionforxcode#47]
Could not locate compile command for /Users/hyou/Dropbox\ (Personal)/dev/Noter/Noter/TagEntryCell.swift at /Users/hyou/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 51. 	main::error(‘Could not locate compile command for /Users/hyou/Dropbox\ (P…’) called at /Users/hyou/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 190 *** Bundle build failed *** Check Bundle project.

Thoughts?

**Comment by johnno1962** [comment]
Hi Seems like you have a project path with special characters in it "()". Move it into your main development area.

**Comment by hyouuu** [comment]
Ah I see thanks. Could we add support to brackets in paths though since
it's my main development area?

**Comment by johnno1962** [comment]
sorry, have tried in the past but found this rather difficult alas.

**Comment by hyouuu** [comment]
So I tried in another folder, and this time got the following issue:

 Connection from: /Users/hyou/Library/Developer/CoreSimulator/Devices/5A02412C-F3D3-4912-9F85-5EF24C9B1F7C/data/Containers/Data/Application/3278CC59-A791-44EE-A156-DE71E37BB872 x86_64 (59) Disconnected from: /Users/hyou/Library/Developer/CoreSimulator/Devices/5A02412C-F3D3-4912-9F85-5EF24C9B1F7C/data/Containers/Data/Application/3278CC59-A791-44EE-A156-DE71E37BB872 Connection from: /Users/hyou/Library/Developer/CoreSimulator/Devices/5A02412C-F3D3-4912-9F85-5EF24C9B1F7C/data/Containers/Data/Application/5E361CD5-0578-4788-9AB3-B3E682FBB296 x86_64 (71) Learnt compile:     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Users/hyou/Dropbox/dev/Noter/Noter/InfoSlider.swift /Users/hyou/Dropbox/dev/Noter/Noter/Button.swift /Users/hyou/Dropbox/dev/Noter/Noter/InlineButtonsController.swift /Users/hyou/Dropbox/dev/Noter/Noter/AppDelegateHelper.swift /Users/hyou/Dropbox/dev/Noter/Noter/NoteMeta.swift /Users/hyou/Dropbox/dev/Noter/Noter/TodoItem.swift /Users/hyou/Dropbox/dev/Noter/Noter/PanelButtonsView.swift /Users/hyou/Dropbox/dev/Noter/Noter/NoteBody.swift /Users/hyou/Dropbox/dev/Noter/Noter/Contact.swift /Users/hyou/Dropbox/dev/Noter/Noter/HelpersDependent.swift /Users/hyou/Dropbox/dev/Noter/Noter/NoteSide.swift /Users/hyou/Dropbox/dev/Noter/Noter/Store.swift /Users/hyou/Dropbox/dev/Noter/Noter/RootViewController.swift /Users/hyou/Dropbox/dev/Noter/Noter/Note.swift /Users/hyou/Dropbox/dev/Noter/Noter/PageContentViewController.swift /Users/hyou/Dropbox/dev/Noter/Noter/Tagger.swift /Users/hyou/Dropbox/dev/Noter/Noter/PageViewController.swift /Users/hyou/Dropbox/dev/Noter/Noter/ImportViewController.swift /Users/hyou/Dropbox/dev/Noter/Noter/TagCell.swift /Users/hyou/Dropbox/dev/Noter/Noter/AddressParser.swift /Users/hyou/Dropbox/dev/Noter/Noter/NoterAppDelegate.swift -primary-file /Users/hyou/Dropbox/dev/Noter/Noter/TagEntryCell.swift /Users/hyou/Dropbox/dev/Noter/Noter/DetailViewController.swift /Users/hyou/Dropbox/dev/Noter/Noter/Helpers.swift /Users/hyou/Dropbox/dev/Noter/Noter/NotesLayout.swift /Users/hyou/Dropbox/dev/Noter/Noter/ContactParser.swift /Users/hyou/Dropbox/dev/Noter/Noter/Cache.swift /Users/hyou/Dropbox/dev/Noter/Noter/Media.swift /Users/hyou/Dropbox/dev/Noter/Noter/VC.swift /Users/hyou/Dropbox/dev/Noter/Noter/TagsViewController.swift /Users/hyou/Dropbox/dev/Noter/Noter/EmblemView.swift /Users/hyou/Dropbox/dev/Noter/Noter/CalendarEventParser.swift /Users/hyou/Dropbox/dev/Noter/Noter/NoteCell.swift /Users/hyou/Dropbox/dev/Noter/Noter/Syncer.swift /Users/hyou/Dropbox/dev/Noter/Noter/Toggles.swift /Users/hyou/Dropbox/dev/Noter/Noter/CalendarEvent.swift /Users/hyou/Dropbox/dev/Noter/Noter/Constants.swift /Users/hyou/Dropbox/dev/Noter/Noter/BackupUtil.swift /Users/hyou/Dropbox/dev/Noter/Noter/Counter.swift /Users/hyou/Dropbox/dev/Noter/Noter/PickerView.swift /Users/hyou/Dropbox/dev/Noter/Noter/Searcher.swift /Users/hyou/Dropbox/dev/Noter/Noter/TodosView.swift /Users/hyou/Dropbox/dev/Noter/Noter/PasscodeViewController.swift /Users/hyou/Dropbox/dev/Noter/Noter/NumDateParser.swift /Users/hyou/Dropbox/dev/Noter/Noter/ColorPicker.swift /Users/hyou/Dropbox/dev/Noter/Noter/ModelParser.swift /Users/hyou/Dropbox/dev/Noter/Noter/Extensions.swift /Users/hyou/Dropbox/dev/Noter/Noter/TextView.swift -target x86_64-apple-ios7.0 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -I /Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Products/Debug-iphonesimulator -F /Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Products/Debug-iphonesimulator -F /Users/hyou/Dropbox/dev/Noter -g -import-objc-header /Users/hyou/Dropbox/dev/Noter/Noter-Bridging-Header.h -module-cache-path /Users/hyou/Library/Developer/Xcode/DerivedData/ModuleCache -D DEBUG -serialize-debugging-options -Xcc -I/Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/Noter-generated-files.hmap -Xcc -I/Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/Noter-own-target-headers.hmap -Xcc -I/Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/Noter-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/Noter-project-headers.hmap -Xcc -I/Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Products/Debug-iphonesimulator/include -Xcc -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/AFNetworking -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/ChameleonFramework -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/UAAppReviewManager -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Advanced -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Advanced/EDAM -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Advanced/Utilities -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Advanced/Utilities/ENMLWriter -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/AFNetworking -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/KSHTMLWriter -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/RMSTokenView -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/SSKeychain -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/Thrift -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/cocoa-oauth -Xcc -I/Users/hyou/Dropbox/dev/Noter/Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/SendToEvernoteActivity -Xcc -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/usr/include/libxml2 -Xcc -I/Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/DerivedSources/x86_64 -Xcc -I/Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/DerivedSources -Xcc -DDEBUG=1 -DINJECTION_BUNDLE -Xcc -DCOCOAPODS=1 -Xcc -working-directory/Users/hyou/Dropbox/dev/Noter -emit-module-doc-path /Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/Objects-normal/x86_64/TagEntryCell~partial.swiftdoc -Onone -module-name Noter -emit-module-path /Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/Objects-normal/x86_64/TagEntryCell~partial.swiftmodule -serialize-diagnostics-path /Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/Objects-normal/x86_64/TagEntryCell.dia -emit-dependencies-path /Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/Objects-normal/x86_64/TagEntryCell.d -emit-reference-dependencies-path /Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/Objects-normal/x86_64/TagEntryCell.swiftdeps -o /Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Intermediates/Noter.build/Debug-iphonesimulator/Noter.build/Objects-normal/x86_64/TagEntryCell.o  real	0m0.776s user	0m0.616s sys	0m0.081s ls: *.framework: No such file or directory  Building iOSInjectionProject/InjectionBundle.xcodeproj xcodebuild  -configuration Debug -arch x86_64 -sdk iphonesimulator  Build settings from command line:     ARCHS = x86_64     SDKROOT = iphonesimulator8.3  === BUILD TARGET InjectionBundle OF PROJECT InjectionBundle WITH CONFIGURATION Debug ===  Check dependencies  CompileC build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/Objects-normal/x86_64/BundleContents.o BundleContents.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler     cd /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject     export LANG=en_US.US-ASCII     export PATH=“/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin”    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wmissing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=5.0 -iquote /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/InjectionBundle-generated-files.hmap -I/Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/InjectionBundle-own-target-headers.hmap -I/Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/InjectionBundle-all-target-headers.hmap -iquote /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/InjectionBundle-project-headers.hmap -iquote.. -I/Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/Debug-iphonesimulator/include -I.. -I../3rdParty -I../Images -I../iOSInjectionProject -I../Noter -I../Noter.xcworkspace -I../NoterTests -I../PendoShare -I../Pods -I../Resources -I../3rdParty/Libraries -I../3rdParty/WeChat -I../Images/Help -I../Images/Inline -I../Images/Type -I../Images/Weather -I../iOSInjectionProject/x86_64 -I../Noter/Images.xcassets -I../Noter/Noter.xcdatamodeld -I../Noter/Settings.bundle -I../Noter.xcworkspace/xcshareddata -I../Noter.xcworkspace/xcuserdata -I../Pods/AFNetworking -I../Pods/ChameleonFramework -I../Pods/evernote-cloud-sdk-ios -I../Pods/Headers -I../Pods/Local\ Podspecs -I../Pods/Target\ Support\ Files -I../Pods/UAAppReviewManager -I../Resources/Fonts -I../Noter/Images.xcassets/AppIcon.appiconset -I../Noter/Images.xcassets/LaunchImage.launchimage -I../Noter/Noter.xcdatamodeld/Noter.xcdatamodel -I../Noter.xcworkspace/xcuserdata/hyou.xcuserdatad -I../Pods/AFNetworking/AFNetworking -I../Pods/AFNetworking/UIKit+AFNetworking -I../Pods/ChameleonFramework/Pod -I../Pods/evernote-cloud-sdk-ios/ENSDK -I../Pods/evernote-cloud-sdk-ios/ENSDKResources.bundle -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios -I../Pods/Headers/Private -I../Pods/Headers/Public -I../Pods/Target\ Support\ Files/Pods -I../Pods/Target\ Support\ Files/Pods-AFNetworking -I../Pods/Target\ Support\ Files/Pods-ChameleonFramework -I../Pods/Target\ Support\ Files/Pods-evernote-cloud-sdk-ios -I../Pods/Target\ Support\ Files/Pods-UAAppReviewManager -I../Pods/UAAppReviewManager/Localization -I../Noter.xcworkspace/xcuserdata/hyou.xcuserdatad/xcdebugger -I../Pods/ChameleonFramework/Pod/Classes -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK -I../Pods/Headers/Private/AFNetworking -I../Pods/Headers/Private/ChameleonFramework -I../Pods/Headers/Private/evernote-cloud-sdk-ios -I../Pods/Headers/Private/UAAppReviewManager -I../Pods/Headers/Public/AFNetworking -I../Pods/Headers/Public/ChameleonFramework -I../Pods/Headers/Public/evernote-cloud-sdk-ios -I../Pods/Headers/Public/UAAppReviewManager -I../Pods/ChameleonFramework/Pod/Classes/Objective-C -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Advanced -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Private -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/SendToEvernoteActivity -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Advanced/EDAM -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Advanced/Utilities -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Private/3rdParty -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/Advanced -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/Private -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/SendToEvernoteActivity -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Advanced -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/SendToEvernoteActivity -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Advanced/Utilities/ENMLWriter -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Private/3rdParty/AFNetworking -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Private/3rdParty/cocoa-oauth -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Private/3rdParty/KSHTMLWriter -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Private/3rdParty/RMSTokenView -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Private/3rdParty/SSKeychain -I../Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Private/3rdParty/Thrift -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/Advanced/EDAM -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/Advanced/Utilities -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Advanced/EDAM -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Advanced/Utilities -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/Advanced/Utilities/ENMLWriter -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/AFNetworking -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/cocoa-oauth -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/KSHTMLWriter -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/RMSTokenView -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/SSKeychain -I../Pods/Headers/Private/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/Thrift -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Advanced/Utilities/ENMLWriter -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/AFNetworking -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/cocoa-oauth -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/KSHTMLWriter -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/RMSTokenView -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/SSKeychain -I../Pods/Headers/Public/evernote-cloud-sdk-ios/ENSDK/Private/3rdParty/Thrift -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/usr/include/libxml2 -I/Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/DerivedSources/x86_64 -I/Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/DerivedSources -F/Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/Debug-iphonesimulator -include /var/folders/g8/rn2dl6f93_v5v3l1mj_1r_mdx32m9p/C/com.apple.DeveloperTools/6.3.2-6D2105/Xcode/SharedPrecompiledHeaders/InjectionBundle-Prefix-cpfmfgghcgjqvqfjlmkdlngxeyvz/InjectionBundle-Prefix.pch -MMD -MT dependencies -MF /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/Objects-normal/x86_64/BundleContents.d —serialize-diagnostics /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/Objects-normal/x86_64/BundleContents.dia -c /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/BundleContents.m -o /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/Objects-normal/x86_64/BundleContents.o  Ld build/Debug-iphonesimulator/InjectionBundle.bundle/InjectionBundle normal x86_64     cd /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject     export IPHONEOS_DEPLOYMENT_TARGET=5.0     export PATH=“/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin”    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -L/Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/Debug-iphonesimulator -F/Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/Debug-iphonesimulator -filelist /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/Objects-normal/x86_64/InjectionBundle.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 x86_64/injecting_class.o -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -F/Users/hyou/Library/Developer/Xcode/DerivedData/Noter-aychxhsvujijnkfebaetbewwenrh/Build/Products/Debug-iphonesimulator -undefined dynamic_lookup -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=5.0 -framework UIKit -framework QuartzCore -framework OpenGLES -framework Foundation -framework CoreGraphics -Xlinker -dependency_info -Xlinker /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/InjectionBundle.build/Debug-iphonesimulator/InjectionBundle.build/Objects-normal/x86_64/InjectionBundle_dependency_info.dat -o /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle.bundle/InjectionBundle ld: framework not found Fabric for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)  GenerateDSYMFile build/Debug-iphonesimulator/InjectionBundle.bundle.dSYM build/Debug-iphonesimulator/InjectionBundle.bundle/InjectionBundle     cd /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject     export PATH=“/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin”     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle.bundle/InjectionBundle -o /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle.bundle.dSYM error: unable to open executable ‘/Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle.bundle/InjectionBundle’: No such file or directory  Touch build/Debug-iphonesimulator/InjectionBundle.bundle     cd /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject     export PATH=“/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin”     /usr/bin/touch -c /Users/hyou/Dropbox/dev/Noter/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle.bundle  ** BUILD FAILED **   The following build commands failed: 	Ld build/Debug-iphonesimulator/InjectionBundle.bundle/InjectionBundle normal x86_64 	GenerateDSYMFile build/Debug-iphonesimulator/InjectionBundle.bundle.dSYM build/Debug-iphonesimulator/InjectionBundle.bundle/InjectionBundle (2 failures) Build Failed with status: 65. You may need to open and edit the bundle project to resolve issues with either header include paths or Frameworks the bundle links against. at /Users/hyou/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 51. 	main::error(‘Build Failed with status: 65. You may need to open and edit t…’) called at /Users/hyou/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 392 *** Bundle build failed *** Check Bundle project.
