### ISSUE TITLE
Build Failed with status: 1

### ISSUE THREAD

**Issue by goktugyil** [johnno1962/injectionforxcode#50]
Hello, I installed it via Alcatraz. Added the main.m, patched the project successfully. But can not make an injection, I get this error. What seems to be the problem?

> Build Failed with status: 1. You may need to open and edit the bundle project to resolve issues with either header include paths or Frameworks the bundle links against. at /Users/gok2/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 51. 	main::error('Build Failed with status: 1. You may need to open and edit th...') called at /Users/gok2/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 392 *** Bundle build failed *** Check Bundle project.

**Comment by johnno1962** [comment]
Hi, just before what you pasted to me there should be a message about why the build failed. Otherwise you can Product/<Project Name>/Open Bundle Project and try to build it to find out what the problem is. This is Swift I take it?

**Comment by goktugyil** [comment]
Yes its Swift. http://prntscr.com/7s7qgs

**Comment by johnno1962** [comment]
Thanks for the screenshot. You need to add the ParseCrashReporting framework to your bundle project so it can link.

**Comment by goktugyil** [comment]
It is already added, included in bridging-header and it is called in the project so it works. Are you referring to something else when you say "add framework to your bundle project"?

http://prntscr.com/7s7y2t

**Comment by johnno1962** [comment]
injection uses a separate “bundle project” in your project root that you need to add the framework to. It will be something like "iOSInjectionProject".

**Comment by goktugyil** [comment]
Thanks

**Comment by ikovalisko** [comment]
@johnno1962, is it enough to add a framework to bundle project or should I modify Framework Search Paths or Header Search Paths?
