### ISSUE TITLE
Cannot get Injection working

### ISSUE THREAD

**Issue by WilliamHua** [johnno1962/injectionforxcode#52]
Hi,

I looked through some of the other issues that had similar problems such as #18 but I haven't been able to find an answer. 

I have a project that uses `Google Maps` (along with a few others installed through `CocoaPods`). I installed Injection through `Alcatraz`, and when I tried following the instructions (building the Injection project) I receive the error: `framework not found GoogleMaps for architecture x86_64`. Do you have any ideas how to fix this?

**Comment by johnno1962** [comment]
Hi, you need to add this framework to your “bundle project”. Please see issue https://github.com/johnno1962/injectionforxcode/issues/50.

**Comment by WilliamHua** [comment]
Oh okay thanks! Didn't see that issue. Just to clarify for anyone else reading this, the frameworks used for the main project needs to also be in the iOSInjection project (which should be inside your main project folder). 

I spent some time installing the ParseCrashReporting framework thinking that was required for the injection to work, but it's whatever frameworks you're using for the parent projects.

**Comment by johnno1962** [comment]
Great. In fact it’s any frameworks that have been @imported as this creates a reference in the object file requiring the bundle linking to know where the framework is. I’ll leave this issue open as it comes up quite a bit.

**Comment by zeshanhayder** [comment]
Error is
Build Failed with status: 65. You may need to open and edit the bundle project to resolve issues with either header include paths or Frameworks the bundle links against. ***

I never get to install this plugin, tried 3-4 times :(. can you please help me ? i want to install this great tool. but sadly it never works on my code.

**Comment by johnno1962** [comment]
Can you show me a bit more of the error please

**Comment by zeshanhayder** [comment]
i uninstalled it for now, i will give you full detail in 5-6 hours as i finish my work. but certainly will do let you know
