### ISSUE TITLE
Can't get injection to work on a Mac app

### ISSUE THREAD

**Issue by chriseidhof** [johnno1962/injectionforxcode#56]
Hey,

I'm on Xcode 7 beta 6 (also tried with Xcode). Somehow I can't get the plugin to work. My friend who is on almost the same setup has no problems. In any case, I found out that the $executable in the per scripts is set to my home dir. I spent a while trying to trace down the problem, but couldn't find it...

As a temporary workaround, I changed this:

    -            if ( status & INJECTION_DEVICEIOS8 ) {
    +            if ( status /*& INJECTION_DEVICEIOS8 */) {

in BundleInjection.h, just to force sending the executable path. By the way, I'm working on a Mac app, not an iOS app.

**Comment by johnno1962** [comment]
Hey Chris, enjoy your talks! I’ve pushed this as a fix for OSX and another for Swift on OSX to keep things rolling. injectionforxcode is in maintenance only mode at the moment - you did well to find the problem. The code could realy do with a fresh start.

**Comment by chriseidhof** [comment]
Thanks for the fix. Yeah it was easy to motivate myself to spend half an hour finding the problem: I know it's going to save me an hour tomorrow ;). Shall we close the issue?
