### ISSUE TITLE
'File not found' error

### ISSUE THREAD

**Issue by DevAlloy** [johnno1962/injectionforxcode#6]
There are no issues in compile, but injection failed.

../HMSideMenuExample/ViewController.h:10:9: fatal error: 'HMSideMenu.h' file not found #import "HMSideMenu.h"   
       ^
 1 error generated.   *\* BUILD FAILED ** 

Looks like trouble apperars when we import source code that lays not in the project folder. When I put all source in project folder issue dissapears.

**Comment by lyahdav** [comment]
I had this issue but I was able to fix without altering the "Header Include Paths". In my case, injection was working fine in Xcode 8, but I was trying to then switch to AppCode.

I was finally able to resolve the issue by making sure I was on the same simulator / iOS version on AppCode and Xcode and I deleted the iOSInjectionProject folder and started from scratch, patching the project in Xcode, ensuring injection works, then patching in AppCode. It worked after all of this, but not sure what step actually fixed the issue.
