### ISSUE TITLE
Is possible flush the UI realtime ?

### ISSUE THREAD

**Issue by gslqy** [johnno1962/injectionforxcode#61]
eg. I have an UIViewController who's title property is @"Title", then modify self.title = @"new title".  type control+=, the UI didn't changed, you must pop the ViewController and reopen it for works. Can I flush the ViewController real time ? like mechanism of lldb [CATransaction flush]

**Comment by johnno1962** [comment]
HI, this isn’t realy possible the way injection works at the moment. You could look at “Eval code” feature of XprobePlugin to do something more like this.
