### ISSUE TITLE
Revert injection's changes does not revert project.pbxproj

### ISSUE THREAD

**Issue by tony--** [johnno1962/injectionforxcode#64]
The GCC_SYMBOLS_PRIVATE_EXTERN entries added to project.pbxproj by [patchProject.pl](https://github.com/johnno1962/injectionforxcode/blob/58209c7f52f122124fcfc4814ed3b4c78ea5581b/InjectionPluginLite/patchProject.pl#L114) are not removed by [revertProject.pl](https://github.com/johnno1962/injectionforxcode/blob/master/InjectionPluginLite/revertProject.pl).

**Comment by johnno1962** [comment]
Hi Tony, This is true. Injection has never reverted this particular change which is required for Injection. It should only affect Debug builds.

**Comment by tony--** [comment]
Thanks for responding, John.  Feel free to close - just noticed while experimenting and thought I would report in case it was an unknown issue that you wanted to address.  
Thanks for sharing this magical project.

**Comment by johnno1962** [comment]
Always happy to see someones awake out there!  Closing..
