### ISSUE TITLE
Cannot inject to device when Product Name has a space

### ISSUE THREAD

**Issue by CraigMason** [johnno1962/injectionforxcode#70]
My InjectionBundle didn't wrap quotes around some of the linker commands, and one of the linker lines caused the compile to fail.

I'm not at the machine right now, but could provider more details if required.

**Comment by johnno1962** [comment]
Hi, Can you send as much detail as possible please to injectionforxcode @ johnholdsworth.com

**Comment by johnno1962** [comment]
Hi, This should be fixed now. Can you give it another try?
