### ISSUE TITLE
Thoughts on using Injection against testing schemes

### ISSUE THREAD

**Issue by orta** [johnno1962/injectionforxcode#77]
A little bit off-topic, but still _on_-topic.

I've been wondering that [Artsy](https://github.com/artsy/mobile/issues/26) should start looking into doing injection based testing, e.g instead of the XCTest runner being a synchronous:

```
app start -> tests start -> tests end  -> app ends
```

it could be more like
```
app start 
  -> tests start -> tests end
  -> tests start -> tests end
  -> tests start -> tests end
  ...
app ends
```

Do you think this is something I could build on top of [Reloader.m](https://github.com/RubyNative/Diamond/blob/master/Reloader/Reloader.m) or would it be better to look into expanding on top/alongside of Injection ( given that it would need a similar "server" architecture that Injection has to receive calls from a plugin )

It's not something I have a tonne of time for right now, but I will with time. So more just opening an idea to try and get some advice.

**Comment by johnno1962** [comment]
Go for it!

**Comment by orta** [comment]
Then I'll be more specific, should I try build this in to injection, or could you imagine it working (reliably) as a separate thing?

**Comment by johnno1962** [comment]
Might be better to make a fresh start, the injection code is getting kind-of crufty. All you need really is Reloader.m and a build log parser which you can get from https://github.com/johnno1962/Refactorator

**Comment by krzysztofzablocki** [comment]
hosted tests are the next big step to happen, it's something that I've been thinking about for a while, if you can make it happen @orta that would be huge :)

**Comment by orta** [comment]
Alright, this discussion doesn't need to be here, there's both a repo, and an issue for my notes over at https://github.com/artsy/mobile/issues/26#issuecomment-229685120
