### ISSUE TITLE
file path when contains '&' it can't tell 

### ISSUE THREAD

**Issue by lacklock** [johnno1962/injectionforxcode#82]
i have some api.swift under "Login&RegisterApi" folder

it can't find the files under this folder

so i only have to change the folder name

**Comment by johnno1962** [comment]
You could try adding & to the list of escaped characters in the script injectSource.pl, line 210:

        (my $escaped = $selectedFile) =~ s/([‘& ])/\\$1/g;

At the moment it only support embedded space and '

**Comment by johnno1962** [comment]
Unfortunately it’s not as easy as this for some reason. It’s going to be easier if you rename the directory :(

**Comment by lacklock** [comment]
thanks any way
