### ISSUE TITLE
Tally Time Saved

### ISSUE THREAD

**Issue by ashfurrow** [johnno1962/injectionforxcode#83]
Hey there! Again, _love_ the project. I was thinking it'd be really cool to tally the time saved (or at least number of compile-relaunch cycles). 

For example, Text Expander has a neat view to see how much time you've saved (roughly):

<img width="543" alt="screen shot 2016-03-10 at 10 44 38 am" src="https://cloud.githubusercontent.com/assets/498212/13676247/05eafb9c-e6b3-11e5-9407-f2f14ddbdab6.png">

It wouldn't need to be anything as complicated, just in a file somewhere maybe. Thoughts?

**Comment by johnno1962** [comment]
Hi Ash, PRs always welcome :+1: Extra points if you could incorporate a billing system of some sort :) 10% of time saved seems reasonable no?

**Comment by ashfurrow** [comment]
I think that's fair, yeah :wink:

**Comment by johnno1962** [comment]
The problem is how to transfer the time saved back into my life. We need some sort of abstract token that relates to time that could be exchanged.

**Comment by ashfurrow** [comment]
It's a pickle for sure. 

Looking through the project, it appears that the best place to add the functionality is in the perl scripts since they do the actual injecting. Probably in `injectSource.pl` near the end? Storing in a text file seems to be the easiest, probably put it in a dot file in the `iOSInjectionProject` directory? Or `iOSInjectionProject/Logs`? I'm thinking of the following few lines:

1. Open the file, if it exists, and parse the number that was there.
1. Increment the number (or set to one if it wasn't loaded).
1. Save the file back. 

First time using Perl in six years but I think I can figure that out :wink: Let me know what you think of the details and I'll move ahead (thanks for your guidance, much appreciated :bow:).
