### ISSUE TITLE
Calculate and display time saved?

### ISSUE THREAD

**Issue by johnno1962** [johnno1962/injectionforxcode#88]
By trapping a couple of Xcode’s internal notifications it is possible to capture a project’s actual build time. This could be passed to the injectSource.pl script as an extra last argument and would make it possible to calculate a running total of the amount of time saved and display it to the user.

**Comment by ashfurrow** [comment]
References for notification names ([from](https://github.com/dbgrandi/GoOutside/blob/9852a04a4b09d711005435c2c52a52f7acbd2d39/GoOutside/GoOutside.m#L90-L98) @dbgrandi): `IDEBuildOperationWillStartNotification` and `ExecutionEnvironmentLastUserInitiatedBuildCompletedNotification`.
