### ISSUE TITLE
Could not codesign

### ISSUE THREAD

**Issue by LinkRober** [johnno1962/injectionforxcode#92]
Renaming bundle so it reloads.. rm -rf "/Users/xiamin/mishios/iOSInjectionProject/build/Debug-iphoneos/InjectionBundle11.bundle" && cp -r "/Users/xiamin/mishios/iOSInjectionProject/build/Debug-iphoneos/InjectionBundle.bundle" "/Users/xiamin/mishios/iOSInjectionProject/build/Debug-iphoneos/InjectionBundle11.bundle" Codesigning with identity 'iPhone Developer: maojian fu (UCB7WMMUAC)' for iOS device iPhone Developer: maojian fu (UCB7WMMUAC): ambiguous (matches "iPhone Developer: maojian fu (UCB7WMMUAC)" and "iPhone Developer: maojian fu (UCB7WMMUAC)" in /Users/xiamin/Library/Keychains/login.keychain)  **\* Could not codesign as 'iPhone Developer: maojian fu (UCB7WMMUAC)': /Users/xiamin/mishios/iOSInjectionProject/build/Debug-iphoneos/InjectionBundle11.bundle **_   at /Users/xiamin/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 57.     main::error('Could not codesign as 9hone Developer: maojian fu (UCB7WMM...') called at /Users/xiamin/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 508 **_ Bundle build failed ***

**Comment by johnno1962** [comment]
Please see https://github.com/johnno1962/injectionforxcode/issues/41

**Comment by robert121** [comment]
ok
