### ISSUE TITLE
i need your help!!!

### ISSUE THREAD

**Issue by lidongxuwork** [johnno1962/injectionforxcode#94]
2016-03-14 22:53:57.387 哈哈哈[8097:472586] +[BundleInjection load] 172.16.3.184 (see project's main.(m|mm)
2016-03-14 22:53:57.390 哈哈哈[8097:472699] Injection attempting connection to: 127.0.0.1:31442
2016-03-14 22:53:57.391 哈哈哈[8097:472699] Connected to "Injection" plugin, ready to load x86_64 code.
objc[8097]: Class ViewController is implemented in both /Users/lidongxu/Library/Developer/CoreSimulator/Devices/BCDBDD48-277A-4176-A7AF-897407D65AE6/data/Containers/Bundle/Application/53D0710E-5E75-4E0C-8CA6-019AB9DB6C9F/哈哈哈.app/哈哈哈 and /Users/lidongxu/Desktop/哈哈哈/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle2.bundle/InjectionBundle. One of the two will be used. Which one is undefined.
14 injections performed so far.
2016-03-14 22:54:05.046 哈哈哈[8097:472586] Ignore any warning, Swizzled ViewController 0x10bdd4348 -> 0x1019c8ad8

**Comment by johnno1962** [comment]
You can ignore this warning. Are things injecting OK?

**Comment by dimohamdy** [comment]
i have same error

**Comment by johnno1962** [comment]
how is it not working?

**Comment by johnno1962** [comment]
Is this the same as https://github.com/johnno1962/injectionforxcode/issues/93

**Comment by dimohamdy** [comment]
@johnno1962  it's work my code in viewdidload not work,when i change method it's work

**Comment by lidongxuwork** [comment]
@dimohamdy Excuse  can you copy your method?

**Comment by lidongxuwork** [comment]
@johnno1962  ok  yes #93 is helped me, thank you very much

**Comment by johnno1962** [comment]
Cool :+1:
