### ISSUE TITLE
_inIPAddresses[] = {"10.12.1.67", "127.0.0.1", 0};

### ISSUE THREAD

**Issue by azxfire** [johnno1962/injectionforxcode#97]
what does all those ip means?I am using my phone developing

**Comment by johnno1962** [comment]
This is the internet address used to connect back to Xcode from your phone. It should be the address of your Mac.

**Comment by azxfire** [comment]
I have changed the ip.And run project then control+= but Injecton Console error *** Could not codesign as 'iPhone Developer': /Users/taowang/Desktop/iBaby/iBaby/iOSInjectionProject/build/Debug-iphoneos/InjectionBundle3.bundle ***

**Comment by johnno1962** [comment]
Start in the simulator and then work your way up to injecting to a device. This issue may help you: https://github.com/johnno1962/injectionforxcode/issues/41

**Comment by azxfire** [comment]
unfortunately,error again
  *** Could not codesign as '': /Users/taowang/Desktop/iBaby/iBaby/iOSInjectionProject/build/Debug-iphoneos/InjectionBundle2.bundle ***   at /Users/taowang/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 57. 	main::error('Could not codesign as  : /Users/taowang/Desktop/iBaby/iBab...') called at /Users/taowang/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 508 *** Bundle build failed ***

**Comment by azxfire** [comment]
I also tried #41 didn't work either

**Comment by johnno1962** [comment]
I think it’s best if you stick to the simulator until you become a bit more familliar with injection.

**Comment by orta** [comment]
Agreed, @azxfire - you're welcome to open another ticket in the future, but I'm closing this for now.
