### ISSUE TITLE
Could not open "iOSInjectionProject/InjectionBundle.xcodeproj/project.pbxproj" as: No such file or directory

### ISSUE THREAD

**Issue by chatwyn** [johnno1962/injectionforxcode#99]
Copying iOSBundleTemplate into project.  
*** Could not open "iOSInjectionProject/InjectionBundle.xcodeproj/project.pbxproj" as: No such file or directory ***   
at /Users/caowenbo/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 57. 	main::error('Could not open "iOSInjectionProject/InjectionBundle.xcodeproj...') called at /Users/caowenbo/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/common.pm line 77 	main::loadFile('iOSInjectionProject/InjectionBundle.xcodeproj/project.pbxproj') called at /Users/caowenbo/Library/Application Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin/Contents/Resources/injectSource.pl line 80
 ***  Bundle build failed  ***

**Comment by johnno1962** [comment]
Hi, try  downloading the plugin from the github source and rebuilding it. This shouldn’t happen!

**Comment by castus** [comment]
Same issue here. I downloaded GitHub source, then build the project, but no luck :(

**Comment by johnno1962** [comment]
Can you delete the iOSInjectionProject and try again?

**Comment by castus** [comment]
I deleted whole project, downloaded Github repo as zip file, than unzip and run. Same error.

**Comment by johnno1962** [comment]
Something is wrong with the plugin build. Sorry to keep saying the obvious but can you delete ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/InjectionPlugin.xcplugin, and rebuild it  using the zipped project. If you want I can TeamView to try to work out the problem.

**Comment by johnno1962** [comment]
BTW, is you project’s .xcodeproj or .xcworkspace in the main directory?

**Comment by liweiBingo** [comment]
I also met this problem

**Comment by castus** [comment]
@johnno1962 I deleted whole project, still have this issue.

**Comment by johnno1962** [comment]
Hi @castus, I appreciate your presistence! The only way to track this down is if I “TeamViewer” onto your machine at some point. If  you’re amenable send your coordinates to injection @ johnholdsworth.com.

**Comment by chatwyn** [comment]
😂

**Comment by dusi** [comment]
Same issue here..for some projects it works, for the one I'd love to use it for it doesn't :) (yes .xcodeproj not workspaces).

I get exactly the same log as above

**Comment by johnno1962** [comment]
The only way to track this down is if I “TeamViewer” onto someone’s machine at some point. If you’re amenable send your coordinates to injection @ johnholdsworth.com.

**Comment by xareelee** [comment]
Same issue here. I think the problem is the file path. There are two **InjectionBundle.xcodeproj** in the `iOSInjectionProject/`:

* one is under `iOSInjectionProject/InjectionBundle.xcodeproj` and that file is empty directory (no .pbxproj).
* the other one is under `iOSInjectionProject/iOSBundleTemplate/InjectionBundle.xcodeproj` and that contains .pbxproj file.

**Comment by johnno1962** [comment]
Hi, Thanks for this. Sheds a little more light on the problem. I’ve made a minor change if you want to try it.

**Comment by dusi** [comment]
It seems like it's fixed the issue for our project...I don't know how to thank you but donate! Thanks John!

**Comment by johnno1962** [comment]
Great news, Donations gratefully accepted on PayPal at: injectionforxcode at johnholdsworth.com 👍

**Comment by xareelee** [comment]
@johnno1962 Thank you. The problem is fixed.

**Comment by castus** [comment]
Fixed, thank you very much 👏
